pingcap/dm

Makefile
Make coveralls token hide
hide token in makefile
Tests 
- No code
=> hide coveralls token

README.md
The two docs links to pingcap.com/docs have been renamed. 
Updated the links.
Tests 
- No code
Code changes
Side effects
=> README: fix dead links

dm/master/server.go, dm/worker/server.go, relay/purger/purger.go, syncer/syncer.go
When I try to fix integration test coverage unstable issue, I found some race condition in code.
Add some lock mechanism
Tests 
=> *: fix some race condition

README.md
fix build status badge link
use right link
Tests 
- No code
=> *: fix build status badge

.github/ISSUE_TEMPLATE/question.md, README.md
- update links to docs in the website
- update links
Tests 
- No code
=> *: update links to docs

loader/checkpoint.go, loader/db.go, loader/loader.go
loader checkpoint init sometimes failed because of concurrent DDL
add retry to loader checkpoint db operation
Tests 
- Unit test
=> loader: add db retry in checkpoint operation

Makefile, tests/README.md, tests/run.sh
There will be more and more integration test cases, we should add an easy way for developer to run single integration test case.
add a parameter to integration_test script
Tests 
=> test: add parameter to run single integration_test

loader/db.go, loader/loader.go
simplify some code
1, if block ends with a break statement, so drop this else and outdent its
block
2, errors.Cause will return the root error
Tests 
Code changes
Side effects
=> loader:/ avoid indent, and confusing causeErr

dm/config/subtask.go, dm/config/task.go, dm/dm-ansible/conf/task.yaml.example, dm/master/task.yaml, dm/tracer/server.go, pkg/tracing/tracer.go, pkg/tracing/tracer_test.go, syncer/heartbeat.go, syncer/syncer.go, tests/README.md, tests/_utils/check_metric, tests/all_mode/conf/dm-task.yaml, tests/all_mode/run.sh, tests/sharding/conf/dm-task.yaml
test syncer heartbeat in integration test
1. turn on `enable-heartbeat` switch
2. make heartbeat interval configurable
Tests 
=> test: add syncer heartbeat test

Makefile, README.md
fix issue #105 
1. rename `make test` to `make unit_test`
2. add new `make test` including `make unit_test` and `make integration_test`
Tests 
- Unit test
- Need to update CI script
=> tests: update test entry in Makefile

dm/worker/subtask.go, syncer/ddl.go, syncer/dml.go
fix some slice prealloc size
1. prealloc slice capacity if we know its final length determinately
2. use `strings.Builder` when we generate column list 
Tests 
- Unit test
=> *: slice capacity prealloc tuning

mydumper/mydumper.go
fix data race
```
WARNING: DATA RACE
Write at 0x00c000c9a590 by goroutine 181:
bytes.(*Buffer).Write()
/usr/local/go/src/bytes/buffer.go:172 +0x42
github.com/pingcap/dm/mydumper.(*Mydumper).spawn()
/home/jenkins/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/mydumper/mydumper.go:138 +0x429
github.com/pingcap/dm/mydumper.(*Mydumper).Process()
/home/jenkins/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/mydumper/mydumper.go:74 +0x26a
Previous write at 0x00c000c9a590 by goroutine 8:
bytes.(*Buffer).ReadFrom()
/usr/local/go/src/bytes/buffer.go:203 +0x4b
io.copyBuffer()
/usr/local/go/src/io/io.go:388 +0x3f5
os/exec.(*Cmd).writerDescriptor.func1()
/usr/local/go/src/io/io.go:364 +0x7a
os/exec.(*Cmd).Start.func1()
/usr/local/go/src/os/exec/exec.go:409 +0x34
Goroutine 181 (running) …
```
=> mydumper: fix data race in stdout pipe

dm/dm-ansible/roles/check_config_static/tasks/main.yml, dm/dm-ansible/start.yml
=> Fix import dashboard

tests/all_mode/run.sh
we introduce rpc check in pr #127, but some tests miss the change
use rpc available check in all the integration tests
Tests 
=> test: use rpc way to check port

Makefile, README.md
we have not unit test coverage report now
upload unit test coverage to codecov
Tests 
- Unit test
=> tests: add unit test coverage report

.codecov.yml
changed code may be not always able to covered by unit test
add codecov config, mainly copy config from TiDB repo
pay attention to two fields
```
+  status:
+    project:
+      default:
+        threshold: 3 #Allow the coverage to drop by threshold%, and posting a success status.
+    patch:
+      default:
+        target: 0%
+    changes: no
```
Tests 
- Unit test
=> tests: add codecov config

checker/checker.go
Eliminate some doubtful logs in checker
add more information into error and log
Tests 
- No code
=> *: refine log of checker

cmd/dm-master/main.go, cmd/dm-tracer/main.go, cmd/dm-worker/main.go, dm/master/status.go, dm/tracer/http_status.go, dm/worker/metrics.go
enable pprof in dm-master, dm-worker, dm-tracer server
add pprof route
Tests 
- Unit test
=> pprof: enable pprof in dm-master and dm-worker

checker/checker.go, cmd/dm-ctl/main.go, dm/config/subtask.go, dm/config/task.go, dm/ctl/ctl.go, go.mod, pkg/func-rollback/rollback.go, pkg/log/log.go, pkg/parser/common.go, pkg/utils/common.go, pkg/utils/printer.go
refactor log of dmctl
use pingcap/log repo
=> *: refactor log of dmctl

dm/worker/server.go
Eliminate some duplicate code reported by `dupl`.
Refactor by extracting a function `mkResponse`.
Tests 
Code changes
Side effects
=> worker: Extract function mkResonse to eliminate duplicate code

dm/config/checking_item.go, dm/config/subtask.go, dm/config/subtask_test.go, dm/dm-ansible/roles/check_config_static/tasks/main.yml, dm/worker/config.go, dm/worker/config_test.go
ref https://github.com/pingcap/dm/issues/141
add source-id length check in
- dm-worker subtask adjust
- dm-worker config verify
- dm-ansible check_config
Tests 
- Unit test
- modify a source-id more than 32 chars in dm-ansible `inventory.ini`
- run `ansible-playbook rolling_update.yml` or `ansible-playbook deploy.yml` 
=> *: add source-id checker

dm/dm-ansible/conf/task.yaml.example, dm/master/task.yaml
refine the sample file of _task.yaml_.
- add comments to explain the schema/table name matching _upstream_ or _downstream_
- add comments to explain the matching rule is _wildcard characters_ or _regular expression_
- make some config items update to date
Tests 
- No code
=> *: refine task.yaml sample file

dm/tracer/config.go, dm/tracer/http_handler.go, dm/tracer/http_status.go, dm/tracer/server.go, dm/tracer/store.go, pkg/tracing/tracer.go, pkg/tracing/tracer_test.go
change log pkg to pingca/log
update dm/tracer and pkg/tracing
=> log refactor: tracer

CHANGELOG.md
- add release notes for 1.0 RC.1
- add release notes for 1.0 RC.1
Tests 
- No code
=> *: add release notes for 1.0 RC.1

dm/dm-ansible/roles/dm-worker/templates/dm-worker.toml.j2
Add new parameters for dm-worker
Only the configuration of dm-worker has been modified, which has no effect on user usage.
@csuzhangxc PTAL
=> Add dm-worker parameters

tests/README.md, tests/_utils/truncate_trace_events, tests/safe_mode/run.sh, tests/sequence_safe_mode/run.sh
fix CI error
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/1599/pipeline
clear trace events after the ddl owner exits, if not, there may exist
trace event records before ddl owner restarts and not meet the test
requirement
Tests 
=> tests: fix safe mode test

dm/dm-ansible/roles/dm-master/defaults/main.yml, dm/dm-ansible/roles/dm-master/templates/run_dm-master.sh.j2, dm/dm-ansible/roles/dm-worker/defaults/main.yml, dm/dm-ansible/roles/dm-worker/templates/run_dm-worker.sh.j2
Fix [TOOL-1424](https://internal.pingcap.net/jira/browse/TOOL-1424)
Save stdout outputs to a separate file.
Tests 
- No code
Code changes
Side effects
=> dm-ansible: Make sure stdout is outputted

loader/checkpoint.go, loader/loader.go, syncer/checkpoint.go, syncer/syncer.go
some db operation misses error scope field.
add error scope when the scope is determined
Tests 
Code changes
Side effects
=> *: fix some error scope in task units

dm/worker/task_checker.go, dm/worker/task_checker_test.go
If the local reader is interrupted from reading a relay log exceeding 4GB and re-reads from a overflow binlog position, DM will meet the following errors:
-  `["error information"="{\"msg\":\"[code=11038:class=functional:scope=internal:level=high] parse relay log file bin.000018 from offset 555 in dir /home/tidb/deploy/relay_log/d2e831df-b4ec-11e9-9237-0242ac110008.000004: parse relay log file bin.000018 from offset 0 in dir /home/tidb/deploy/relay_log/d2e831df-b4ec-11e9-9237-0242ac110008.000004: parse relay log file /home/tidb/deploy/relay_log/d2e831df-b4ec-11e9-9237-0242ac110008.000004/bin.000018: binlog checksum mismatch, data may be corrupted` if the invalid binlog offset doesn't exceed the relay log file size
- ` ["error information"="{\"msg\":\"[code=11038:class=functional:scope=inte …
=> DM-worker: update blacklist of auto resumable error

dm/worker/task_checker.go, tests/_utils/check_log_contains, tests/_utils/run_tidb_server, tests/all_mode/run.sh, tests/run.sh
add integration test for task auto recover
add a test in `all_mode`
Tests 
=> test: add integration test for task auto recover

dm/worker/log.go, dm/worker/meta_test.go, loader/convert_data.go, pkg/streamer/reader.go, relay/metrics.go, syncer/sharding-meta/shardmeta.go, syncer/sharding_group.go, syncer/syncer.go
fix misspell, make some log clearer
fix word spelling only
Tests 
- Unit test
Code changes
Side effects
=> *: fix some misspell

CHANGELOG.md
Add DM 1.0 GA in CHANGELOG
Tests 
- Unit test
- No code
Code changes
Side effects
=> Changelog: Add DM 1.0 GA

dm/dm-ansible/inventory.ini
release DM/dm-ansible v1.0.0
update `dm_version` from `latest` to `v1.0.0` in _inventory.ini_.
Tests 
- No code
=> ansible: release v1.0.0

CHANGELOG.md
Add 1.0 GA upgrade action required in CHANGELOG.
=> Add 1.0 GA action required in CHANGELOG

CHANGELOG.md
cherry-pick  https://github.com/pingcap/dm/pull/273 to release-1.0
=> CHANGELOG: Add action required  (#273)

dm/dm-ansible/inventory.ini
release dm-ansible v1.0.1
update `dm_version` from `v1.0.0` to `v1.0.1` in inventory.ini.
Tests 
- No code
=> ansible: release v1.0.1

loader/db.go, pkg/baseconn/conn.go, pkg/baseconn/conn_test.go, syncer/checkpoint_test.go, syncer/db.go, syncer/syncer_test.go
cherry pick #280 into release-1.0
=> conn: add max idle conn config (#280)

CHANGELOG.md
=> Changelog: Add 1.0.1

syncer/syncer.go
cherry-pick: [PR](https://github.com/pingcap/dm/pull/289) split DDL sync from sync function
Tests 
- Unit test
- No code
Code changes
Side effects
=> cherry-pick: split DDL sync from sync function

go.mod, go.sum
1. Fix processing header only, no checksum binlog event. ref: https://github.com/siddontang/go-mysql/pull/431
2. update TiDB parser
```bash
go get -u github.com/siddontang/go-mysql@master
go get -u github.com/pingcap/parser@master
go mod tidy
```
Tests 
- Unit test
Code changes
Side effects
=> *: update go.mod

README.md, checker/checker.go, dm/ctl/master/update_task.go, dm/dm-ansible/conf/task.yaml.example, dm/master/task.yaml
column mapping is not recommend to use, remove it in example config file and help output
remove it
cherry pick from #299 
=> .*: remove column mapping in example config file and help output (#299)

dm/dm-ansible/inventory.ini
release DM-ansible v1.0.2
update `dm_version` in DM-ansible's `inventory.ini` from `v1.0.1` to `v1.0.2`
Tests 
- No code
=> ansible: release v1.0.2

pkg/parser/common.go, pkg/parser/common_test.go
`ast.AlterDatabaseStmt` type is not supported in DM parse util pkg
Add `*ast.AlterDatabaseStmt` in type switch
Tests 
- Unit test
Code changes
Side effects
=> pkg: support alter database in parser util pkg

go.mod, go.sum
TiDB-Tools have updated some error messages: https://github.com/pingcap/tidb-tools/pull/295
This PR updates dm's go.mod to get these new features.
Tests 
- Unit test
=> go.mod:update go.mod and go.sum to new tidb-tools

dm/dm-ansible/inventory.ini
release DM-ansible v1.0.3
update `dm_version` in DM-ansible's inventory.ini from `v1.0.2` to `v1.0.3`.
Tests 
- No code
=> ansible: release v1.0.3

cmd/dm-worker/main.go, dm/master/config.go, dm/master/coordinator/coordinator.go, dm/master/coordinator/worker.go, dm/master/server.go, dm/pb/dmmaster.pb.go, dm/pb/dmmaster.pb.gw.go, dm/pb/dmworker.pb.go, dm/pb/tracer.pb.go, dm/pb/tracer_base.pb.go, dm/pb/tracer_syncer.pb.go, dm/proto/dmmaster.proto, dm/worker/config.go, dm/worker/join.go, dm/worker/server.go, dm/worker/worker.go
part of make DM HA.
- `dm-worker` start will register to the master
- `dm-worker` will keepalive with master after the start
- `dm-master` will get the event and set the worker status.
Tests 
to be added.
- Unit test
=> *: Register DM-worker instance into DM-master

dm/common/common.go, dm/common/common_test.go, dm/config/mysql_config.go, dm/master/coordinator/coordinator.go, dm/master/election.go, dm/master/server.go, dm/worker/join.go, dm/worker/server.go
Signed-off-by: nolouch <nolouch@gmail.com>
coordinator startup:
- only leader startup 
- recover the registered workers and their binding relationship,
Tests 
- Unit test
=> *: refine coordinator startup

generate-dm.sh
Allow `generate-dm.sh` to work in Windows (`make retools_setup` on Windows produces `*.exe` files).
Generalize `generate-dm.sh`.
Tests 
* the new script works on Windows.
Code changes
Side effects
=> generate-dm.sh: allow running this script on Windows bash (MSYS2)

go.mod, go.sum
In #404, we have updated tidb-tools to support wildcard matching better. We should update tidb-tools dependency to use these new features.
Update tidb-tools dependency in go.mod.
Tests 
- Unit test
=> go.mod: update tidb-tools dependency to v3.0.11

dm/dm-ansible/inventory.ini
update `dm_version` in DM-ansible's inventory.ini from `v1.0.3` to `v1.0.4`.
Tests 
- No code
=> ansible: release v1.0.4

dm/dm-ansible/inventory.ini
update `dm_version` in DM-ansible's `inventory.ini` from `v1.0.4` to `v1.0.4-hotfix`.
Tests 
- No code
=> ansible: update `dm_version` to `v1.0.4-hotfix`

dm/master/scheduler/scheduler_test.go, go.mod, go.sum
https://github.com/pingcap/dumpling/pull/53
dumpling's `bytes.Buffer` has a bug and has been fixed now.
Update dumpling's dependency to fix this bug.
Tests 
- Unit test
=> dumpling/: update dumpling dependency

tests/others_integration.txt, tests/run.sh
extract `ha_cases` from `others_integration.txt` to a separate CI pipeline stage.
- remove `ha_cases` from `others_integration.txt`
- add a CI pipeline stage
- NOTE: this case will not exist in `release-1.0`, so I also update `tests/run.sh` and catch some exception in CI
Tests 
- No code
=> *: extract ha_cases from others_integration.txt

tests/run.sh
cherry-pick #593 and resolve conflicts.
---
extract `ha_cases` from `others_integration.txt` to a separate CI pipeline stage.
- remove `ha_cases` from `others_integration.txt`
- add a CI pipeline stage
- NOTE: this case will not exist in `release-1.0`, so I also update `tests/run.sh` and catch some exception in CI
Tests 
- No code
=> *: extract ha_cases from others_integration.txt (#593)

dm/dm-ansible/scripts/dm.json, relay/metrics.go
fix two issues for metrics:
- add `task` filter for `binlog event size`.
- register `binlogTransformDurationHistogram` for relay.
as above.
Tests 
- Unit test
=> *: fix metrics

dm/dm-ansible/scripts/dm.json, dm/master/config.go, dm/master/dm-master.toml
change `e,g.` to `e.g.` in master
change `binlog replication`  to `binlog replication unit` like other description in dm-ansible/scripts/dm.json 
Tests 
- No code
=> master,ansible:minor suggestion for help message

CHANGELOG.md
- add release notes for v1.0.5
- add release notes for v1.0.5
Tests 
- No code
=> CHANGELOG: add release notes for v1.0.5

tests/_utils/run_sql_file
tests/: fix the wrong port argument in tests/_utils/run_sql_file
Tests 
- Unit test
=> fix wrong port

go.mod, go.sum, pkg/shardddl/optimism/lock_test.go
https://github.com/pingcap/dm/issues/634
https://github.com/pingcap/tidb-tools/pull/338
Update dependency and add a UT.
Tests 
- Unit test
=> pkg/shardddl: make optimistic shard ddl able to handle `MODIFY COLUMN` from `INT` to `BIGINT`

cmd/dm-ctl/main.go, dm/config/subtask.go, dm/config/subtask_test.go, dm/ctl/common/config.go, dm/master/server_test.go, dm/portal/api.go, dm/worker/config.go, dm/worker/config_test.go, dm/worker/relay.go, dm/worker/worker.go, pkg/utils/encrypt.go, tests/dmctl_basic/conf/dm-worker1.toml, tests/dmctl_command/conf/dm-worker1.toml, tests/dmctl_command/run.sh
manual cherry merge PR #633 to `release-1.0`
=> feat: manual cherry merge PR #633 to `release-1.0`

dm/master/election.go, dm/master/election_test.go, pkg/election/election.go
resign from leader when fail to start, #527 , #674
when fail to start scheduler/pessimist/optimist, resign the leader
Tests 
- Unit test
Code changes
=> dm-master: resign from leader when fail to start

syncer/syncer.go
#701 
simply remove neddResync func and continue to get binlog event.
Tests 
- Unit test
=> syncer: remove needResync

syncer/syncer.go
manually cherrypick #716 
Tests 
- Unit test
=> manually cherrypick #716

dm/ctl/master/query_error.go, dm/ctl/master/query_status.go, dm/unit/unit.go
manualy cherrypick #546 
use terror.Message(err) to replace errors.ErrorStack(err) in
- NewProcessError
- dm/ctl/master/query_error.go
- dm/ctl/master/query_status.go
Tests 
- Unit test
=> error_message: cherry pick #546

CHANGELOG.md
add the change log for v1.0.6
add the change log for v1.0.6
Tests 
- No code
=> CHANGELOG: add release notes for v1.0.6

dm/ctl/common/util.go, dm/ctl/master/break_ddl_lock.go, dm/ctl/master/check_task.go, dm/ctl/master/migrate_relay.go, dm/ctl/master/pause_relay.go, dm/ctl/master/pause_task.go, dm/ctl/master/purge_relay.go, dm/ctl/master/query_error.go, dm/ctl/master/query_status.go, dm/ctl/master/refresh_worker_tasks.go, dm/ctl/master/resume_relay.go, dm/ctl/master/resume_task.go, dm/ctl/master/show_ddl_locks.go, dm/ctl/master/sql_inject.go, dm/ctl/master/sql_replace.go, dm/ctl/master/sql_skip.go, dm/ctl/master/start_task.go, dm/ctl/master/stop_task.go, dm/ctl/master/switch_relay_master.go, dm/ctl/master/unlock_ddl_lock.go, dm/ctl/master/update_masterconfig.go, dm/ctl/master/update_relay.go, dm/ctl/master/update_task.go, dm/master/server.go, dm/tracer/server.go, dm/worker/server.go
manaully cherrypick #746
remove stack information of error message
Tests 
- Unit test
=> cherry pick remove stack err

syncer/syncer.go
manually cherrypick #731
Tests 
- Unit test
=> .*: fix gorountine leak

tests/README.md
provide more detailed instructions.
1. mention version limit
2. provide URL for MySQL settings
Tests 
- No code
Code changes
Side effects
=> doc: provide more detailed instructions

.github/pull_request_template.md
fix a typo
fix a typo
Tests 
- No code
Code changes
Side effects
=> doc: fix a typo in pull_request_template.md

_utils/terror_gen/errors_release.txt, pkg/atomic2/atomic.go, pkg/atomic2/atomic_test.go, pkg/terror/error_list.go, syncer/syncer.go, tests/filter_user_cancel/conf/diff_config.toml, tests/filter_user_cancel/conf/dm-master.toml, tests/filter_user_cancel/conf/dm-task.yaml, tests/filter_user_cancel/conf/dm-worker1.toml, tests/filter_user_cancel/conf/dm-worker2.toml, tests/filter_user_cancel/data/db1.increment.sql, tests/filter_user_cancel/data/db1.prepare.sql, tests/filter_user_cancel/data/db1.prepare.user.sql, tests/filter_user_cancel/data/db2.increment.sql, tests/filter_user_cancel/data/db2.prepare.sql, tests/filter_user_cancel/data/db2.prepare.user.sql, tests/filter_user_cancel/run.sh, tests/incremental_mode/run.sh, tests/others_integration.txt
manually cherry-pick #794, and seperate test case (mainly copied from incremental_mode)
Tests 
Code changes
Side effects
=> *: detect user cancel and omit according error #794

dm/master/server.go, dm/master/server_test.go
fix the unit test https://github.com/pingcap/dm/issues/773#issuecomment-655873038
I run this test case 30 times in my local computer, and it all run success.
evict leader for master which is to be offline
Tests 
- Unit test
=> master: fix unit test for OfflineMember

Makefile, dm/config/source_config.go, dm/ctl/master/operate_source.go, dm/master/source.toml, tests/dmctl_basic/check_list/operate_source.sh
close #782 
- add print-sample-config flag for operate-source
Tests 
=> source: add print-sample-config flag for operate-source

dm/master/scheduler/scheduler_test.go, pkg/ha/keepalive_test.go, tests/sequence_sharding/run.sh
part of #773, fix some fail of https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/5672/pipeline/70/
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/5854/pipeline/87/
increase timeout param
Tests 
- Unit test
Code changes
Side effects
=> test: increase waiting time

tests/all_mode/run.sh
remove repeated lines in test `all_mode`
remove
Tests 
Code changes
Side effects
=> test: remove repeated lines

loader/checkpoint.go, syncer/checkpoint.go, syncer/online_ddl.go, syncer/sharding-meta/shardmeta.go, syncer/sharding_group.go, tests/all_mode/run.sh
re-implement #835 , please check if changes are proper.
back quote and escape MySQL identifier
Tests 
Code changes
Side effects
=> *: back quote and escape MySQL identifier #835

cmd/dm-ctl/main.go, cmd/dm-master/main.go, cmd/dm-tracer/main.go, cmd/dm-worker/main.go
manually cherrypick #822 
change ErrorStack to terror.Message for flag
=> remove stack error for flag (#822)

dm/master/server_test.go
add log to investigate test fail of `(*testMaster).TestOperateSource`
Tests 
- Unit test
Code changes
Side effects
=> test: add log to investigate test fail

dm/master/server_test.go
part of https://github.com/pingcap/dm/issues/773
sort response so `DeepEqual` won't fail on reversed order
Tests 
- Unit test
Code changes
Side effects
=> test: fix TestOperateSource

dm/ctl/common/util.go, dm/worker/worker_test.go
~~fix test TestTaskAutoResume not waiting so long w.r.t checking interval~~ and adding another yaml suffix
Tests 
- Unit test
Code changes
Side effects
=> *: fix test and yaml suffix

dm/master/ddl_lock.go, dm/master/server.go, pkg/shardddl/optimism/keeper.go, pkg/shardddl/pessimism/keeper.go, pkg/utils/common.go, tests/sequence_sharding_optimistic/run.sh
check shard mode for `unlock-ddl-lock`, give better message on non-supported (optimistic currently) sharding mode
extract task from lock-ID and get shard mode from task config
Tests 
Code changes
Side effects
=> *: check shard mode for `unlock-ddl-lock`

README.md
update build status icon in README
Tests 
- No code
Code changes
Side effects
=> README: update build status icon

syncer/syncer.go, tests/shardddl1/run.sh
ignore TRUNCATE TABLE in optimistic mode
filter out this statement in pre-check part
Tests 
Code changes
Side effects
=> syncer: ignore TRUNCATE TABLE in optimistic mode

dm/config/task.go, dm/master/server.go, pkg/utils/util.go, pkg/utils/util_test.go, tests/_utils/check_log_not_contains, tests/all_mode/run.sh
- replace password with '******' in log
NOTE: support dumpling later
Tests 
- Unit test
=> log: hide password in log

dm/ctl/common/config.go, dm/ctl/ctl.go, dm/ctl/master/check_task.go, dm/ctl/master/get_task_config.go, dm/ctl/master/handle_error.go, dm/ctl/master/list_member.go, dm/ctl/master/offline_member.go, dm/ctl/master/operate_leader.go, dm/ctl/master/operate_schema.go, dm/ctl/master/operate_source.go, dm/ctl/master/pause_task.go, dm/ctl/master/query_status.go, dm/ctl/master/resume_task.go, dm/ctl/master/show_ddl_locks.go, dm/ctl/master/start_task.go, dm/ctl/master/stop_task.go, dm/ctl/master/unlock_ddl_lock.go, tests/dmctl_advance/check_list/unlock_ddl_lock.sh
[docs#261](https://github.com/pingcap/docs-dm/pull/261)
- update help message of command
=> dmctl: update help message of command

Makefile, _utils/mod_check/check.sh, _utils/terror_gen/check.sh, dumpling/dumpling.go, go.mod, go.sum, tests/all_mode/run.sh
update dumpling and omit password
Tests 
=> dumpling: hide password in dumpling log

syncer/checkpoint.go
https://github.com/pingcap/dm/pull/916#issuecomment-679465185
fix above data race
add locks for `LoadMeta()` and other methods
Tests 
- pass original tests
Code changes
Side effects
=> checkpoint: fix data race

syncer/checkpoint.go
cherry-pick #925 
---
https://github.com/pingcap/dm/pull/916#issuecomment-679465185
fix above data race
add locks for `LoadMeta()` and other methods
Tests 
- pass original tests
Code changes
Side effects
=> checkpoint: fix data race (#925)

_utils/terror_gen/errors_release.txt, errors.toml, pkg/terror/error_list.go, tests/full_mode/run.sh
part of https://github.com/pingcap/dm/issues/773, fix `full_mode`
log shows both worker has encountered dumpling error, but sometimes the result of RPC lack one failure, so I guess sometimes RPC returns too fast.
remove the immediately check, later check could has same promise.
Tests 
Code changes
Side effects
=> test: move status check later

dm/config/task.go, dm/worker/worker.go, dumpling/dumpling.go, tests/drop_column_with_index/conf/dm-task.yaml, tests/drop_column_with_index/run.sh
cherry-pick #909
part of https://github.com/pingcap/dm/issues/907
retrieve ANSI_QUOTES from upstream, and change subtask config.
disable manually config EnableANSIQuotes of subtask
Tests 
Code changes
Side effects
=> dump: retrieve ANSI_QUOTES from upstream (#909)

go.mod, go.sum
update tidb-tools to support AWS privileges
Tests 
- No code
Code changes
Side effects
=> dep: update tidb-tools to support AWS privileges

dm/ctl/master/query_status.go, dm/ctl/master/show_ddl_locks.go, tests/dmctl_basic/check_list/query_status.sh, tests/dmctl_basic/check_list/show_ddl_locks.sh
forget to apply to `query-status`, `show-ddl-locks` (not include disabled commands).
Tests 
Code changes
Side effects
=> command: support task-file for more command

dm/worker/server.go, dm/worker/worker.go, pkg/ha/bound.go, pkg/ha/keepalive.go, pkg/ha/stage.go, pkg/shardddl/optimism/info.go, pkg/shardddl/optimism/operation.go, pkg/shardddl/optimism/table.go, pkg/shardddl/pessimism/info.go, pkg/shardddl/pessimism/operation.go
fix #960 
check channel closed in `select{}`, use `case .* := <-` to search `*.go` except `*_test.go`, some chan will not close so omitted
Tests 
- Pass original test
Code changes
Side effects
=> *: check channel closed in select{}

dm/dm-ansible/inventory.ini
- update `dm_ansible` for DM-ansible to `v2.0.0-rc.2`.
Tests 
- No code
=> ansible: update dm_version to v2.0.0-rc.2

CHANGELOG.md
add 2.0.0-rc.2 release notes
copied from https://github.com/pingcap/docs-dm/pull/331.
Tests 
- No code
=> CHANGELOG: add 2.0.0-rc.2 release notes

dm/master/server.go, dm/pb/hide_password.go, pkg/utils/util.go
extract common logic to a function, if in future we will change some logic in this function it would be easier.
close #811 
use `runtime` and `reflect` to achieve this
Tests 
- pass original test
Code changes
Side effects
=> master: extract common logic to a function

dm/common/common_test.go
part of #998 
Tests 
- Unit test
=> test: improve common unit test coverage to 81.2%

go.mod, go.sum, tests/print_status/run.sh
fix #997 and https://github.com/pingcap/dumpling/pull/150
update dependency
Tests 
- No code
Code changes
Side effects
=> dep: update dumpling to fix null string error

pkg/conn/baseconn_test.go, pkg/conn/basedb_test.go
part of #998 
improve coverage to 71.4% for pkg/conn
Tests 
- Unit test
Code changes
Side effects
=> test: improve coverage to 71.4% for pkg/conn

_utils/terror_gen/errors_release.txt, checker/check_test.go, errors.toml, pkg/terror/error_list.go
part of #998 
Tests 
- Unit test
=> test: improve unit test coverage of checker

dm/config/task_test.go
improve coverage for dm/config, very tough work...
part of #998 improve coverage to 73.4% only run this folder's test
Tests 
- Unit test
Code changes
Side effects
=> test: improve coverage to 73.4% for dm/config

_utils/terror_gen/errors_release.txt, dm/config/task.go, dm/master/bootstrap.go, dm/master/scheduler/scheduler.go, errors.toml, loader/loader.go, pkg/dumpling/utils.go, pkg/terror/error_list.go, pkg/upgrade/upgrade.go, pkg/upgrade/upgrade_test.go, pkg/upgrade/version.go, pkg/utils/util.go, pkg/v1dbschema/schema.go, syncer/checkpoint.go, syncer/checkpoint_test.go, syncer/mode.go, syncer/syncer.go, syncer/syncer_test.go, tests/import_v10x/run.sh
manually cherry-pick #988
---
Tests 
- Unit test
- No code
Code changes
Side effects
=> *: save exitSafeModeLoc in checkpoint, load it, upgrade strategy (#988)

pkg/etcdutil/etcdutil.go, pkg/etcdutil/etcdutil_test.go, syncer/status.go
part of #998
- improve pkg/etcdutil unit test coverage to 88%
- remove some redundant code in syncer
Tests 
- Unit test
Code changes
Side effects
=> test: improve pkg/etcdutil unit test coverage to 87%

README.md
add slack badge to introduce more developer
Tests 
- No code
Code changes
Side effects
=> README: add slack badge

loader/checkpoint.go, loader/loader.go, loader/util.go, tests/all_mode/run.sh
found ERROR in log, which caused by bug in https://github.com/pingcap/dm/pull/1027.
Tests 
Code changes
Side effects
- Need to cherry-pick to the release branch #1043
=> loader, test: fix bug of clean dump file and update checkpoint

README.md, dm/master/workerrpc/workerrpc_test.go
part of #998 
- improve `master/workerrpc` unit test coverage to 91%
Tests 
- Unit test
Code changes
Side effects
=> test: improve master/workerrpc unit test coverage to 91%

syncer/checkpoint_test.go, syncer/error.go, syncer/error_test.go
part of #998
Tests 
- Unit test
Code changes
Side effects
=> test: improve coverage of syncer/error.go to 89.6%

syncer/handle_error_test.go
part of #998 
Tests 
- Unit test
=> test: add syncer/handle_error unit test

.github/workflows/chaos-mesh.yml
- cache go modules and retool for github actions workflow
Tests 
- No code
Code changes
Side effects
=> actions: cache go modules and retool

pkg/dumpling/utils.go, pkg/dumpling/utils_test.go
support metadata without GTID
Tests 
- Unit test
Code changes
Side effects
=> dumpling: support metadata without GTID

Makefile
if we have version info in integration test logs, we may debug easier.
add version info into the integration test binaries
Tests 
- No code
=> *: add version info into the integration test binaries

README.md
reduce installing guide diverging
Tests 
- No code
Code changes
Side effects
=> README: unify installing steps with doc

pkg/retry/errors.go, syncer/error.go, tests/handle_error/run.sh
some of our hard coded string are not suitable for tidb v3
change them
Tests 
- Integration test in https://github.com/pingcap/dm/pull/1158
Code changes
Side effects
=> *: support TiDB v3 error message

go.mod, go.sum, syncer/ddl.go, tests/_utils/run_sql_file_online_ddl
close #1175 
update parser to https://github.com/pingcap/parser/pull/1061
Tests 
Code changes
Side effects
=> syncer: split DDL after fetching online DDL to execute

loader/loader.go
fix nil map after clone. We may found more map or develop a safe clone in future
Tests 
Code changes
Side effects
=> loader: fix nil map after clone

.github/workflows/chaos-mesh.yml, dm/master/election.go, dm/master/scheduler/scheduler.go, dm/master/shardddl/optimist.go, dm/master/shardddl/pessimist.go, pkg/parser/common.go, tests/shardddl3/run.sh
fix #1185 
- don't forbid DM-master leader startup for unexpected DDL locks
Tests 
- Unit test
Code changes
Side effects
=> fix: don't forbid DM-master leader startup for unexpected DDL locks

loader/loader.go, loader/status.go, loader/util.go, syncer/syncer.go, tests/full_mode/run.sh
- loader progress show NaN % if no data in all tables
- syncer log Dpanic when create database
Tests 
=> log: fix NaN and Dpanic log

tests/shardddl3/run.sh
add more shard DDL test cases.
after this PR and #1171, all of shard DDL test cases in https://internal.pingcap.net/jira/browse/TICASE-4046 (internal only) will become closed or canceled.
Tests 
- No code
Code changes
Side effects
=> add two shard DDL test cases

loader/loader.go, loader/status.go, loader/util.go, syncer/syncer.go, tests/full_mode/run.sh
cherry-pick #1201 to release-2.0
- loader progress show NaN % if no data in all tables
- syncer log Dpanic when create database
Tests 
=> log: fix NaN and Dpanic log #1201

tests/_utils/test_prepare, tests/ha_cases/run.sh
implement some cases in [TICASE-913 (internal only)](https://internal.pingcap.net/jira/browse/TICASE-913)
Tests 
Code changes
Side effects
=> test: implement some test cases about config name

tests/import_v10x/run.sh
manually cherry-pick #1232 to release-2.0 (can't wait that merged)
---
after https://github.com/pingcap/tidb/issues/20446, check of `SHOW CREATE TABLE` should alter some text
Tests 
Code changes
Side effects
=> test: update check text to latest tidb (#1232)

tests/import_v10x/run.sh
after https://github.com/pingcap/tidb/issues/20446, check of `SHOW CREATE TABLE` should alter some text
Tests 
Code changes
Side effects
=> test: update check text to latest tidb

.github/challenge-bot.yml
high performance challenge need this label
Tests 
- No code
Code changes
Side effects
=> .github: add default sig label

go.mod, go.sum
update dumpling to 10/28
Tests 
- No code
Code changes
- Has exported function/method 
Side effects
=> dep: update dumpling to 10/28

dm/dm-ansible/inventory.ini
update `dm_ansible` for DM-ansible to v2.0.0
Tests 
- No code
Code changes
Side effects
=> ansible: update dm_version to v2.0.0

CHANGELOG.md
add 2.0 release note
Tests 
- No code
Code changes
Side effects
=> CHANGELOG: add 2.0 release note

tests/all_mode/run.sh, tests/import_v10x/run.sh, tests/shardddl1/run.sh
manually cherry-pick #1251
---
different tidb version will output different error message
will cherry-pick to 2.0 manually
Tests 
Code changes
Side effects
=> test: relax error message for more tidb version (#1251)

tests/all_mode/run.sh, tests/import_v10x/run.sh, tests/shardddl1/run.sh
different tidb version will output different error message
will cherry-pick to 2.0 manually
Tests 
Code changes
Side effects
=> test: relax error message for more tidb version

roadmap.md
update roadmap because v2.0 GA has been released
Tests 
- No code
Code changes
Side effects
=> *: update roadmap

loader/loader.go
fix part2 of #1262, the scenario:
1. worker-A reported error via `runFatalChan`
2. cancel the context
3. chan received in worker-B exit
4. chan sender in worker-B blocked
always wait for the sender to exit in the receiver for load unit
Tests 
- Unit test
Code changes
Side effects
=> fix: always wait for the sender to exit in the receiver for load unit

loader/checkpoint.go, loader/checkpoint_test.go, loader/loader.go, loader/util.go, tests/all_mode/run.sh
manually cherry-pick #1042 #1145 to release-1.0
---
Tests 
- Unit test
- No code
Code changes
Side effects
=> loader: fix bug of checkpoint, cherry-pick to 1.0 (#1042)(#1145)

pkg/binlog/event/util.go, pkg/binlog/event/util_test.go
close #1275 
handle `OVER_MAX_DBS_IN_EVENT_MTS` separately
Tests 
- Unit test
Code changes
Side effects
=> utils: support OVER_MAX_DBS_IN_EVENT_MTS (254) in binlog

.github/workflows/chaos-mesh.yml
coredns may be failed in chaos mesh tests, like https://github.com/pingcap/dm/runs/1444275245?check_suite_focus=true
wait more time for coredns.
Tests 
- No code
Code changes
Side effects
=> chaos: wait coredns more time

syncer/syncer.go, tests/incremental_mode/run.sh
fix #1254
do not try to handle jobs anymore if the context is done
Tests 
- Unit test
**NOTE**: this case is hard to test in CI now, `incremental_mode` may have a little effect on this.
Code changes
Side effects
=> syncer: do not try to handle jobs anymore if the context is done

pkg/utils/util.go, syncer/filter_test.go
partitial cherry-pick of https://github.com/pingcap/dm/pull/1331
filter out EVENT by builtin RE
Tests 
- Unit test
Code changes
Side effects
=> utils: filter out EVENT

.github/workflows/upgrade-via-tiup.yml
https://github.com/pingcap/dm/actions/runs/439062347
reproduce firstly
Tests 
- github action
=> test: fix upgrade tidb via tiup

dm/dm-ansible/inventory.ini
update the version for DM-Ansible
Tests 
- No code
Code changes
Side effects
=> ansible: update the version for DM-Ansible

dm/ctl/master/purge_relay.go, tests/dmctl_basic/check_list/purge_relay.sh
We only support purge to filename in purge-relay now.
So some error msg should be changed
Tests 
- manually test the command
=> purge-relay: update purge relay command args

CHANGELOG.md
Tests 
- No code
Code changes
Side effects
=> CHANGELOG: add v2.0.1 release note

checker/check_test.go
follow up #1366
change to unorder match
Tests 
- Unit test
Code changes
Side effects
=> test: fix test isn't suitable for an unordered output

chaos/cases/task.go
chaos unstable
decrease time for incremental round
Tests 
- chaos
=> chaos: half time per round

README.md
add more info
add more info
Tests 
- Unit test
- No code
Code changes
Side effects
=> README: add more info

.github/workflows/check-and-build.yml
Add CI job for building DM on both Ubuntu and macOS.
Tests 
- Unit test
- No release note
=> ci: build on both Ubuntu and macOS

dm/ctl/master/pause_relay.go, dm/ctl/master/purge_relay.go, dm/ctl/master/resume_relay.go, pkg/streamer/hub.go, tests/dmctl_basic/conf/dm-task.yaml, tests/dmctl_basic/conf/get_task.yaml, tests/dmctl_basic/run.sh
Align capital letter amd enable a test for `purge-relay`
Tests 
- No code
Code changes
Side effects
=> dmctl: refine help message and enable test

dm/ctl/master/pause_relay.go, dm/ctl/master/purge_relay.go, dm/ctl/master/resume_relay.go
address comments in https://github.com/pingcap/docs-dm/pull/560
add `.`
Tests 
- No code
Code changes
Side effects
=> dmctl: add ending peroid

dm/master/config.go, tests/ha_master/run.sh, tests/tls/run.sh
temporary fix of #1458
use `false` `EnableGRPCGateway`
Tests 
=> master: disable grpc gateway of embedded etcd

tests/all_mode/run.sh
add a test about pause/resume relay when sync data
Tests 
- No code
Code changes
Side effects
=> test: add a test about pause/resume relay when sync data

syncer/job.go, syncer/job_test.go, syncer/optimist.go, syncer/syncer.go, tests/handle_error/run.sh
show origin ddl when ddl error occur, so user can use handle-error replace with them
return origin ddl when error
Tests 
=> error: show origin ddl when error

relay/relay.go, tests/all_mode/conf/source1.yaml, tests/all_mode/data/db1.increment0.sql, tests/all_mode/data/db2.increment0.sql, tests/all_mode/run.sh
just a test, to verify https://github.com/pingcap/dm/issues/1524
check we continue on latest relay log (`.000002`)
Tests 
Code changes
Side effects
=> test: when VIP upstream switching, continue from relay.meta

dumpling/dumpling.go, dumpling/dumpling_test.go, go.mod, go.sum
update dependency of dumpling, and set default rows to 200000
Tests 
- Unit test
Code changes
Side effects
=> dep: update dumpling dependency

tests/tiup/upgrade-from-v1.sh
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/sudo/sudo_1.8.27-1+deb10u2_amd64.deb  404  Not Found [IP: 151.101.250.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Tests 
- https://github.com/pingcap/dm/actions/runs/732012827
=> test: run apt update to avoid outdated link

dm/dm-ansible/inventory.ini
=> ansible: Update inventory.ini

CHANGELOG.md
Tests 
- Unit test
- No code
Code changes
Side effects
=> CHANGELOG: fix wrong date

.github/workflows/upgrade-via-tiup.yml, CHANGELOG.md
- forget a space in release note
- forget to update previous versions in CI
Tests 
- No code
=> CHANGELOG, actions: fix some typo when release

.github/workflows/chaos-mesh.yml, .github/workflows/check-and-build.yml
part of https://github.com/pingcap/dm/issues/1579
- update cache because of they fixed BUG
- skip outdated actions from PR
Tests 
- No code
=> actions: skip outdated actions and update version of an action

dm/master/server.go, tests/sequence_sharding_optimistic/run.sh, tests/sequence_sharding_removemeta/data/db1.increment2.sql, tests/sequence_sharding_removemeta/run.sh
close https://github.com/pingcap/dm/issues/1543
skip this check
Tests 
=> master: support unlock-ddl-lock after stop-task

Makefile, go.mod, go.sum
fix master build error 
* go mod
* update `github.com/go-mysql-org/go-mysql` version to delete `github.com/myesui/uuid` dep
Tests 
- No code
=> dep: update go-mysql

tests/README.md, tests/all_mode/run.sh
- None
Currently we cannot dynamically change the configuration by setting environment variables in integration tests case,
beacuse we have lot's of hard code in yaml conf file , for examle: [source1.yaml](https://github.com/pingcap/dm/blob/master/tests/all_mode/conf/source1.yaml)
Tests 
- No code
Code changes
- None
Side effects
- None
=> *: update run integration_test doc

.github/workflows/upgrade-via-tiup.yml, CHANGELOG.md
=> CHANGELOG: update release note for 2.0.3

.golangci.yml
remove golangci-lint `nolintlint` plugin because it's strange behaviour...
Tests 
- No code
Code changes
- None
Side effects
- None
=> lint: remove nolintlint

pkg/schema/tracker.go, pkg/schema/tracker_test.go
close #1696 
use CreateTableWithInfo API provided by TiDB
Tests 
- Unit test
Now create 100 tables cost 13 seconds
=> tracker: speed up create table by lower api

tests/_utils/run_dm_ctl_with_retry, tests/_utils/wait_process_exit, tests/gtid/run.sh, tests/ha/run.sh, tests/sharding/run.sh
fix some unstable test [jenkins](https://ci.pingcap.net/blue/organizations/jenkins/dm_ghpr_new_test/detail/dm_ghpr_new_test/230/pipeline/980)
* ha
* gtid
* sharding
- sleep in it test cace 
Tests 
- No code
Code changes
- None
Side effects
- None
=> tests: fix some unstable test

README.md
We'll deprecate the TiDB Monthly Update, so I remove the link.
Tests 
- Unit test
- No code
Code changes
Side effects
=> README: remove TiDB Monthly and add case studies

.github/workflows/upgrade-via-tiup.yml, dm/ctl/common/config.go, tests/dmctl_command/run.sh, tests/tiup/upgrade-from-v2.sh
#1720 
as title
Tests 
- Unit test
Code changes
-None
Side effects
- None
=> dmctl: try read master addr from env

.github/workflows/binlog-999999.yml, .github/workflows/chaos-mesh.yml, .github/workflows/upgrade-via-tiup.yml, .github/workflows/upstream-switch.yml, CONTRIBUTING.md, Dockerfile, go.mod, go.sum, step_by_step_contribute.md, tests/tiup/docker/control/Dockerfile, tests/tiup/docker/node/Dockerfile, tools/go.mod
close https://github.com/pingcap/dm/issues/1686
simply search and replace 1.13 to 1.16
Tests 
- No code
=> *: update go version to 1.16

_utils/terror_gen/errors_release.txt, errors.toml, go.mod, go.sum, pkg/terror/error_list.go, syncer/streamer_controller.go, syncer/syncer.go, tests/incremental_mode/run.sh
close https://github.com/pingcap/dm/issues/1682
add workaround for the error caused by go-mysql
Tests 
=> syncer: update dependency to avoid exit when meet unsupported binlog

relay/metrics.go
https://asktug.com/t/topic/93363/7
wrap the ticker listener in for loop so we can continuously receive the events.
Tests 
- Manual test (TODO)
Code changes
Side effects
=> relay: fix bug of relay metrics being recorded only once

syncer/mode.go, syncer/syncer_test.go, tests/print_status/run.sh
related to https://github.com/pingcap/dm/issues/1757
as title
Tests 
Code changes
Side effects
=> syncer: adjust safemode duration to 2 * checkpointFlushInterval

CHANGELOG.md
Tests 
Code changes
Side effects
=> changelog: add change log for v2.0.4

.github/workflows/upgrade-via-tiup.yml, CHANGELOG.md, tests/tiup/upgrade-from-v1.sh
=> changelog: add change log for v1.0.7

.github/workflows/upgrade-via-tiup.yml
Tests 
- No code
Code changes
Side effects
=> test: add v2.0.4 in tiup upgrade test

syncer/syncer.go, tests/only_dml/conf/dm-task.yaml, tests/only_dml/run.sh
close #1798 
as title
Tests 
Code changes
Side effects
=> syncer: fix syncer not being triggered by ticker

syncer/sharding-meta/shardmeta.go, tests/shardddl1_1/run.sh
close #1785 
if `len(source items)>len(global items)`, which means it's a new DDL for all sources, we simply add it to global items
Tests 
=> pessimist: Fix Inconsistent DDL sequence error if same DDL replicate twice in sequence-sharding

_utils/terror_gen/errors_release.txt, errors.toml, loader/checkpoint.go, loader/loader.go, pkg/terror/error_list.go, tests/load_interrupt/run.sh
close #1770
when loader checkpoint `UpdateOffset` meet error, just return that error and Pause the task
Tests 
Code changes
Side effects
=> loader: fix loader painc when not remove meta

pkg/schema/tracker_test.go, tests/adjust_gtid/run.sh
part of https://github.com/pingcap/dm/issues/1790
- increase time limit for create table
- in adjust_gtid test, because worker maye exit too early, so we can't check metrics.
Tests 
- No code
Code changes
Side effects
=> test: fix two unstable tests

README.md
as title
as title
Tests 
- No code
Code changes
- None
Side effects
- None
-None
=> doc: fix test readme link

syncer/dml.go, syncer/syncer.go, syncer/syncer_test.go, tests/expression_filter/run.sh
as title
as title
Tests 
Side effects
=> syncer: print number of filtered row changes in log

_utils/terror_gen/errors_release.txt, errors.toml, pkg/terror/error_list.go
close https://github.com/pingcap/dm/issues/1807
add "walkaround" field for an error
Tests 
- No code
Code changes
Side effects
=> terror: add a walkaround to indicate not all dm-master are up

.github/workflows/binlog-999999.yml, chaos/manifests/sources.yaml
revert after TiDB support utf8mb3, https://github.com/pingcap/tidb/issues/26226
=> pin mariadb version in chaos

.github/workflows/upstream-switch.yml
as title
Tests 
- No code
Code changes
Side effects
=> ci: fix release ci

.github/workflows/binlog-999999.yml, .github/workflows/chaos-mesh.yml, .github/workflows/check-and-build.yml, .github/workflows/upgrade-via-tiup.yml, .github/workflows/upstream-switch.yml
as title
Tests 
- No code
Code changes
Side effects
=> ci: bump action-tmate to v3

tests/case_sensitive/run.sh
Add retry for the run_sql check to avoid check before sync finished.
Tests 
Code changes
Side effects
=> fix unstable test case_sensitive

.github/workflows/binlog-999999.yml, .github/workflows/chaos-mesh.yml, .github/workflows/check-and-build.yml, .github/workflows/upgrade-via-tiup.yml, .github/workflows/upstream-switch.yml, Dockerfile, tests/_utils/send_lark_notify.go
as title
* get committer from github.event.puhser.name
* remove mydmber from docker image
* add `dm-master/dm-worker/dmctl` to image `/bin`
Tests 
- Manually test ci [here](https://github.com/Ehco1996/dm/runs/3129916613?check_suite_focus=true)
Code changes
Side effects
=> chore: get real committer name && optimise dockerfile

syncer/mode.go, syncer/syncer.go, tests/safe_mode/conf/source1.yaml, tests/safe_mode/conf/source2.yaml
Store safe-mode struct in sync to avoid depending on the safe-mode struct in event context.
Set safe-mode value by the current snapshot safe-mode value .
Tests 
- Unit test
- No code
Code changes
Side effects
=> fix safe mode

CHANGELOG.md
=> .*: update change-log for v2.0.5

.github/workflows/upgrade-via-tiup.yml
=> test: add upgrade test for v2.0.5

README.md
=> README: update go version

pkg/election/election.go
close https://github.com/pingcap/dm/issues/1212
https://github.com/pingcap/dm/issues/1212#issuecomment-894051100
try to manually resign, after we returned from `Campaign`
Tests 
- hard to test, maybe we can check unstable CI is gone.
=> election: try manually resign

CHANGELOG.md
=> .*: update changelog for v2.0.6

CHANGELOG.md, pkg/shardddl/optimism/keeper.go, pkg/shardddl/optimism/lock.go, tests/shardddl1/run.sh
cherrypick #1971 and #1990 to release-2.0.6
=> cherrypick #1971 and #1990 to release-2.0.6

.github/workflows/upgrade-via-tiup.yml
=> test: add upgrade test for v2.0.6

syncer/syncer.go, tests/metrics/run.sh
part of https://github.com/pingcap/dm/issues/1997
Reduced test instability by skipping `HeartbeatEvent` 
Tests 
Code changes
Side effects
=> test: fix unstable test metrics

.github/workflows/upgrade-via-tiup.yml
as title
cd to working dir
Tests 
test ci [here](https://github.com/Ehco1996/dm/runs/3367299609?check_suite_focus=true)
- No code
Code changes
Side effects
=> test: fix ci lark push

tests/incremental_mode/run.sh, tests/sequence_sharding_optimistic/run.sh
we injected some error that will only take effect once. So if we retry resuming the error will be skipped
Tests 
- No code
=> test: fix unstable retry resume-task

syncer/syncer.go, tests/_utils/check_ticker_interval, tests/metrics/run.sh
as title
To meet the demanding conditions of the test scenario
only events like `WriteRowsEventV2` are now handled in the code by using failpoint
Tests 
Code changes
Side effects
=> test: fix metrics again

dm/config/subtask.go, dm/config/subtask_test.go
close https://github.com/pingcap/dm/issues/2034
add AdjustOnlineDDL in upgrade
Tests 
=> config: adjust OnlineDDL in subtask config

relay/relay.go, relay/writer/file.go, tests/sharding2/conf/source2.yaml, tests/sharding2/run.sh
close #2136 
reset meta after purgeRelayDir like we do in [reSetupMeta](https://github.com/pingcap/dm/blob/9fe475a41369f88692b9ab6d62ed847492918082/relay/relay.go#L647)
Tests 
=> relay: fix `no such file or directory` for start-relay command

CHANGELOG.md, dm/ctl/common/config.go
typo fix
typo fix, replace `dmtcl` with `dmctl`
Tests 
- No code
=> dmctl: typo fix

CHANGELOG.md, _utils/terror_gen/errors_release.txt, dm/config/subtask.go, dm/config/task.go, dm/config/task_test.go, errors.toml, pkg/terror/error_list.go, syncer/job.go, syncer/online-ddl-tools/online_ddl.go, syncer/syncer_test.go, tests/dmctl_basic/conf/get_task.yaml, tests/import_goroutine_leak/run.sh, tests/import_v10x/conf/task.yaml
cherry-pick #2139 and add change log for v2.0.7
=> .*: cherry-pick #2139 and update change log for v2.0.7

Makefile, tools/Makefile, tools/go.mod, tools/go.sum, tools/tools.go
as title
can preview this CI in [here](https://ci.pingcap.net/blue/organizations/jenkins/dm-verify-ci-test/detail/dm-verify-ci-test/7/pipeline/21)
Tests 
- No code
Code changes
Side effects
=> test: support verify CI
