syncer/syncer_test.go
```
mysql> insert into tztest_1.t_1(id, a) values (2, '1990-04-15 02:30:12');
ERROR 1292 (22007): Incorrect datetime value: '1990-04-15 02:30:12' for column 'a' at row 1
mysql> select @@global.sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@global.sql_mode                                                                                                                         |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION | …
```
=> test: fix Incorrect datetime value error in unit test

syncer/ddl_test.go, syncer/filter.go, syncer/filter_test.go
Previously, we skipped all queries begin with `#` as a comment.
But, a query starts with `#` may be a valid DDL or DML, like
```
CREATE TABLE do_db.do_table (c1 INT)
```
So, we can not simply skip it.
- remove `#` from the `builtInSkipDDLs`
- let the caller decide whether needing to skip the query
Tests 
- Unit test
---
In our current integration test framework, comments start with `#` line will be ignored by the *mysql* client, then no comments will stay in binlog events. So, add such a test case has no meaning.
=> syncer: do not skip all queries begin with '#'

syncer/db.go
for to mysql 8 compatibility
mysql 8 , show binary logs,One more field
Log_name,File_size,Encrypted
in order to avoid
```
sql: expected 3 destination arguments in Scan, not 2
```
=> syncer: take the first 2 fields of show binary logs

pkg/streamer/utils.go
`fileSizeUpdated` returns the file size change status and error, but we have different error semantics, sometime it is unexpected execution error, sometime it is file size unexpected change error.
use the right return value
Tests 
- Unit test
=> *: fileSizeUpdated return value minor fix

syncer/dml.go, syncer/syncer.go, syncer/syncer_test.go, tests/_utils/run_dm_worker, tests/all_mode/data/db1.increment.sql
Currently we remove all generated column for DML, but generated column in where condition is valid.
- keep generated column in index searching
- keep generated column in where condition when generating `update`/`delete` DML
Tests 
Side effects
=> syncer: fix generated column in where condition

dm/worker/subtask.go
try to resume task if sync unit exits with `invalid connection` error
it's a poor and very rough retry feature, the main reason is that the concurrency control of the sub task module is very confusing and needs to be optimized. After improve its state transition and concurrency control, I will optimize the implementation of retry feature.
Tests 
- set up a dm cluster
- start a task
- interfere network to let connetion timeout
- check whether dm-worker would try to resume task
=> poor: resume task if sync unit exits with `invalid connection` error

Makefile
go module may be downloaded during `go vet` test and these download/extract information should be ignored in fail detect
remove stdout, check stderr only in `go vet` bash pipeline.
ref: https://stackoverflow.com/a/8535532/1115857
Tests 
- Unit test
=> *: fix go vet test in CI

Makefile
go module download information writes to tty directly, so we use tee
to redirect stderr for fail detect
fix issue in https://github.com/pingcap/dm/pull/76.
because go module download information does not go to stdout/stderr directly, we always get these messages from bash pipeline
use /dev/stderr to filter real error messages.
Tests 
- Unit test
=> *: fix go vet test

loader/loader.go
if we pause/resume task when loading, the **progress** may show an incorrect value. It's because we forgot to reset `totalDataSize`/`finishedDataSize` when resuming.
reset `totalDataSize`/`finishedDataSize` when resuming.
Tests 
- `pause-task` when loading
- `resume-task`
- observe `finishedBytes`/`totalBytes`/`progress` in `query-status`'s output
=> loader: fix load progress

dm/tracer/server.go, pkg/tracing/tracer.go, pkg/tracing/tracer_test.go
Some imports of `"golang.org/x/net/context"` remained, causing go.mod to automatically include `golang.org/x/net` again.
They were accidentally reintroduced because #58 was merged after #75.
Replaced the remaining imports of `"golang.org/x/net/context"` by `"context"`.
Tests 
- Unit test
Code changes
Side effects
=> tracer: remove remaining imports of golang.org/x/net/context

mydumper/mydumper.go
Fix #83.
Instruct mydumper to write log into `/dev/stderr`. Then, change dm_worker to read lines from the child process's `stderr`, and convert into the corresponding `log.*` call.
Note, unlike the description of #83, in this PR
* `mydumper-$task.log` is no longer created
* logs of all levels (INFO and DEBUG) will be written into `dm-worker.log`, if enabled.
Tests 
- Integration test (checked that mydumper logs exist in `dm-worker.log` when running `make integration_test`)
Code changes
Side effects
=> mydumper: pipe mydumper log into dm-worker.log

pkg/binlog/reader/reader.go, pkg/binlog/reader/tcp.go, pkg/binlog/reader/tcp_test.go, relay/relay.go
This PR is a part work of #91 
Introduced a binlog event `Reader` interface, so we can implement at least 3 kinds of Reader later:
1. TCPReader: read binlog events from a master server through TCP stream
2. FileReader: read binlog events from binlog files (or relay log files)
3. InMemoryReader: read binlog events from memory, used as a mock master to do testing
In this PR, I only implement a `TCPReader` and refactor a litter code for relay writer to make review easier.
Later, the following things will be done:
1. split relay writer to _reader_ --> _translator_ --> _writer_
2. add an InMemoryReader to test 3 parts above
3. refactor sync unit (relay reader) to read through a FileReader and use an InMemoryReader to test it
- add a `TCPReader`
- refactor relay writer to use the `TCPReader` …
=> relay: use Reader interface read binlog events

syncer/sharding_group.go
Previous it logged the `ddl` constant in `job.go` making the error message always showing "... and current ddl ddl for source table ..." which is useless. It is supposed to log the parameter `ddls`.
Replaced "ddl" with "ddls".
Tests 
- Unit test
* And mainly verified that `Printf("%q", []string{"a", "b"})` has the desired output.
Code changes
Side effects
=> syncer: fix the error message about executing multiple DDLs

dm/config/task.go, dm/master/server.go
avoid panic mentioned in #97 
- adjust subtask config when generating from task config
- show error stack for start/update task in dmctl
Tests 
- start task with un-encrypted downstream password
=> config: verify subtask config when generating from task

dm/dm-ansible/scripts/dm.json, syncer/metrics.go, syncer/syncer.go
Support to judge whether waiting for sharding DDL lock to be resolved through metrics.
- add metrics for sharding merge
Tests 
1. observe `dm_syncer_unsynced_table_number`/`dm_syncer_shard_lock_resolving`
2. execute DDL for a part of shard tables
3. observe `dm_syncer_unsynced_table_number`/`dm_syncer_shard_lock_resolving`
4. execute DDL for all other shard tables
5. observe `dm_syncer_unsynced_table_number`/`dm_syncer_shard_lock_resolving`
Side effects
=> syncer: add metrics for sharding merge

dm/config/subtask.go, dm/config/subtask_test.go, dm/worker/config.go, loader/checkpoint_test.go, loader/db.go, syncer/db.go, syncer/syncer_test.go
the default value of `max_allowed_packet` in MySQL server and _go-sql-driver/mysql_ driver is 4MB, but in TiDB server it's 64MB.
ref:
- <https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_allowed_packet>
- <https://github.com/go-sql-driver/mysql#maxallowedpacket>
- change the default value of `max_allowed_packet` to 64MB
- in fact, in the clinet this can be 1GB, ref <https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_allowed_packet>
- add a `max-allowed-packet` config item for DB config
- change `charset` from `utf8` to `utf8mb4`
we can refactor DB operation to a pkg and add test cases for config later.
Tests 
- config with/without `max_allowed_packet` in DM-worker's config and …
=> *: change `max_allowed_packet` to 64MB

dm/config/subtask.go, dm/master/task.yaml, loader/loader.go
when running multiple tasks, the user may specify the same `loader.dir` between tasks, then the dumped data maybe overwrote.
- append a `.name` prefix to the `loader.dir` if not exists
Tests 
- start a full/all task
- observe the dumped data dir name
=> *: add a `.name` suffix to avoid data overwrite between tasks

dm/ctl/master/migrate_relay.go, dm/worker/config.go, dm/worker/server.go, pkg/binlog/event/dml.go, pkg/binlog/event/util.go, pkg/encrypt/encrypt.go, pkg/streamer/reader.go, pkg/streamer/utils_test.go
use tool https://github.com/mdempsky/unconvert we can find some unnecessary type conversion
remove unnecessary type conversion, it is safe because go is a statically typed programming language
two code snippets are not changed for readability and understandability
```
/home/apple/work/code/pingcap/gopath/src/github.com/pingcap/dm/syncer/dml.go:359:33: unnecessary conversion
data = strconv.FormatInt(int64(v), 10)
^
/home/apple/work/code/pingcap/gopath/src/github.com/pingcap/dm/syncer/dml.go:367:35: unnecessary conversion
data = strconv.FormatUint(uint64(v), 10)
```
Tests 
- Unit test
=> *: remove some unnecessary type conversion

syncer/dml.go
https://internal.pingcap.net/jira/browse/TOOL-1078
```
"msg": "gen insert sqls failed: insert columns and data mismatch in length: 32 (columns) vs 33 (data), schema: ctmg, table: np_bas_person\ngithub.com/pingcap/dm/syncer.(*Syncer).Run\n\t/home/jenkins/workspace/build_dm_master/go/src/github.com/pingcap/dm/syncer/syncer.go:1185\ngithub.com/pingcap/dm/syncer.(*Syncer).Process\n\t/home/jenkins/workspace/build_dm_master/go/src/github.com/pingcap/dm/syncer/syncer.go:451\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"}
```
mysql
```
ERROR 1136 (21S01): Column count doesn't match value count at row 1
```
change to more clear msg like mysql
Tests 
Code changes
Side effects
=> syncer/dml.go: Refine error msg

tests/README.md, tests/_utils/check_metric, tests/all_mode/run.sh
in all mode test, DM-worker is just restarted before checking metric, the metric may have not been updated in time.
add retry in metric check
Tests 
=> tests: add retry in metric check, make it more robust

dm/dm-ansible/scripts/dm.json, dm/dm-ansible/scripts/dm_instances.json, dm/dm-ansible/scripts/import_grafana_dashboards.py
refine the dashboard
- only show instances for the selected task
- add the description for metrics
- add an overview monitoring for the task
- see screenshot below
- add a board for the status of the instance
- see screenshot below
Tests 
- run some tasks
- observe the dashboard
=> *: refine dashboard

dm/config/subtask.go, dm/config/task.go, dm/worker/meta.go, dm/worker/meta_test.go
when auto stating task from the meta, the DM-worker may panic because no `max-allowed-packet` is set.
```
github.com/pingcap/dm/loader.createConn(0xc00054a000, 0x0, 0xc0004ac000, 0x3400008)
/Users/zhangxc/gopath/src/github.com/csuzhangxc/dm/loader/db.go:199 +0xea
github.com/pingcap/dm/loader.newRemoteCheckPoint(0xc00054a000, 0xc00053e0a0, 0xe, 0xc0005427e0, 0x1eb1a20, 0x2162ac0, 0xc00027b380)
/Users/zhangxc/gopath/src/github.com/csuzhangxc/dm/loader/checkpoint.go:73 +0x35
github.com/pingcap/dm/loader.(*Loader).Init(0xc00009c270, 0x0, 0x0)
/Users/zhangxc/gopath/src/github.com/csuzhangxc/dm/loader/loader.go:363 +0xf5
github.com/pingcap/dm/dm/worker.(*SubTask).Init(0xc0000e8c60, 0x0, 0x0)
/Users/zhangxc/gopath/src/github.com/csuzhangxc/dm/dm/worker/subtask.go:111 +0xdf …
```
=> *: fix adjusting sub task config when starting task from the meta

dm/dm-ansible/scripts/dm.json, dm/dm-ansible/scripts/dm_instances.json
now we have two dashboards, then change `DM` to `DM-task` is better.
- change dashboard name from `DM` to `DM-task`.
- also, change name from `DM-instances` to `DM-instance`
Tests 
- No code
=> dashboard: change dashboard name

pkg/encrypt/encrypt_test.go
sometimes unit test in decrypt_test.go failed as following:
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/test_dm_master/detail/test_dm_master/75/pipeline/44
This is because we check whether the 16th char in decrypt text is '@'
https://github.com/pingcap/dm/blob/a5578266da5a08706b82ff8d65fb166b1a9a7975/pkg/encrypt/encrypt.go#L77
but in our test decrypt text, the 17th char could also be '@'
This commit only removes all '@' char from test decrypt text, which ensures the unit test case will always run successfully.
Tests 
- Unit test
=> tests: fix random fail in decrypt unit test

dm/worker/worker.go, pkg/tracing/tracer.go, tests/README.md, tests/_utils/test_prepare, tests/all_mode/conf/dm-task.yaml, tests/online_ddl/conf/dm-task.yaml, tests/safe_mode/run.sh, tests/sharding/conf/dm-task.yaml
fix data race
```
WARNING: DATA RACE
Read at 0x00c0000e30c8 by goroutine 130:
github.com/pingcap/dm/pkg/tracing.(*Tracer).AddJob()
/home/apple/work/code/pingcap/gopath/src/github.com/pingcap/dm/pkg/tracing/tracer.go:232 +0x1c4
github.com/pingcap/dm/pkg/tracing.(*Tracer).CollectSyncerBinlogEvent()
/home/apple/work/code/pingcap/gopath/src/github.com/pingcap/dm/pkg/tracing/tracer_syncer.go:54 +0x3c5
github.com/pingcap/dm/syncer.(*Syncer).Run()
/home/apple/work/code/pingcap/gopath/src/github.com/pingcap/dm/syncer/syncer.go:1156 +0x20d3
github.com/pingcap/dm/syncer.(*Syncer).Process()
/home/apple/work/code/pingcap/gopath/src/github.com/pingcap/dm/syncer/syncer.go:473 +0x7b1
Previous write at 0x00c0000e30c8 by goroutine 29:
github.com/pingcap/dm/pkg/tracing.(*Tracer).newJobChans() …
```
=> tracer: fix data race, start tracer before task restore

Makefile, go.mod, go.sum
one of failpoint commit changes Eval returns sequence, but doesn't synchronize change in runtime, which will lead to following error and CI failure
```
loader/loader.go:140: non-bool ok (type failpoint.Value) used as if condition
loader/loader.go:141: invalid type assertion: val.(int) (non-interface type bool on left)
```
we should unify failpoint to the latest version, both in command line tool and runtime
Tests 
- Unit test
=> *: upgrade failpoint dep

syncer/sharding_group.go, syncer/sharding_group_test.go
when multiple sharding group exists, the global may be updated incorrectly.
fix global checkpoint adjusts in `lowestFirstPosInGroups`.
Tests 
- Unit test
=> syncer: fix checkpoint update when multi sharding group exists

dm/dm-ansible/unsafe_cleanup.yml
Users can unsafe_cleanup the dm module using the new adding yml file in ansible
Add a file named unsafe_cleanup.yml in ansible
Tests 
ansible-playbook unsafe_cleanup.yml
=> Add unsafe_cleanup.yml for dm ansible

go.mod, go.sum, pkg/log/log.go, syncer/checkpoint.go, syncer/checkpoint_test.go, syncer/syncer.go, syncer/syncer_test.go, tests/README.md, tests/wait_for_mysql.sh
re-enable checkpoint unit test. ~But after this change, we must setup two MySQLs for unit test~
~1. change `To DB` config in unit test, use TiDB as default~
1. use sqlmock in checkpoint test
2. LoadMeta test fix.
3. test save older point
Tests 
- Unit test
- should update jenkins CI config, add another MySQL server in Unit test
=> tests: re-enable checkpoint unit test

tests/all_mode/run.sh, tests/incremental_mode/run.sh, tests/load_interrupt/run.sh, tests/online_ddl/run.sh, tests/print_status/conf/dm-task.yaml, tests/print_status/run.sh, tests/safe_mode/run.sh, tests/sharding/run.sh
fix occasional CI failed, such as https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/726/pipeline
after dig into log, I find syncer log is not flushed to disk during test running in time.
1. disable heartbeat in `print_status` test, so we will have determined binlog event counts
2. add retry mechanism in syncer print status check
3. **update DM-worker, DM-master startup and check rpc available sequence** to following
```
start DM-worker1
check DM-worker1 rpc service is available
start DM-worker2
check DM-worker2 rpc service is available
start DM-server
check DM-server rpc service is available
```
btw, why there are 92 binlog events in test case but there exists 94 SQL statements, this is because the following two statements change zero …
=> tests: fix print_status check, in some case log may not flushed to disk

dm/worker/worker.go, pkg/binlog/reader/tcp.go, relay/relay.go
in DM-worker `UpdateRelayConfig` function, the check of `update source ID is not allowed` is before new config loaded, which will always fail.
Besides I find we will get the following error after we update a relay config. This is caused by we forget to close binlog replication syncer after relay paused
```
2019/05/10 06:19:52.383 relay.go:176: [error] [relay] process exit with error ERROR 1236 (HY000): A slave with the same server_uuid/server_id as this slave has connected to the master; the first event 'bin.000007' at 27622680, the last event read from './bin.000007' at 27622993, the last byte read from './bin.000007' at 27622993.
github.com/pingcap/errors.AddStack
/root/.gvm/pkgsets/go1.12/global/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/errors.Trace …
```
=> *: fix update relay processing order

loader/loader.go
`dump` and `load` unit in DM-worker use different black-white list config,  so dumped files may not contain SQL files we want to use in loader.
The root solution should unify the task config used in `dump` unit and `load` unit, which needs a lot of work and will not be done in this pr.
In this pr we only refine the error messages to help DBA to distinguish different error scenario.
Tests 
- start a fresh task with `full` mode, set `extra-args: "-m"` config in dump unit. see error message.
- start a fresh task with `full` mode, dump schema that does not list in load unit do-dbs. see error message.
=> loader: refine some error messages

loader/loader.go, loader/util.go, loader/util_test.go
mydumper will not dump schema create sql sometimes, and then loader will return error.
fix issue https://internal.pingcap.net/jira/browse/TOOL-1316 
create schema create sql file if not find
Tests 
- Unit test
- Manual test
=> loader: generate db-schema-create.sql file if not exists

loader/db.go, loader/loader.go
"break" statement terminates execution of the innermost "for", "switch" or "select" statement. We should cancel execution when `context.Done` is detected.
1. fix a break wrong usage
2. remove some unused code
3. use a range operator to simplify single case in `for { select {} }`
Tests 
- Unit test
=> loader: fix break in forloop and some minor refine

go.mod, go.sum, syncer/syncer_test.go
support case insensitive binlog event in binlog event filter. fix issue https://github.com/pingcap/dm/issues/181
upgrade the version of tidb-tools to this commit https://github.com/pingcap/tidb-tools/tree/16523947c844b1b1aa2996f56dbdc4251bb5c452
Tests 
- Unit test
=> syncer: support case insensitive binlog event in filter

dm/config/subtask_test.go, dm/master/server.go, dm/tracer/server.go, dm/worker/config_test.go, dm/worker/log_test.go, dm/worker/meta_test.go, loader/loader.go, pkg/binlog/reader/file_test.go, pkg/binlog/reader/tcp_test.go, pkg/encrypt/encrypt.go, pkg/streamer/file_test.go, pkg/streamer/streamer_test.go, pkg/tracing/tracer_test.go, relay/metrics.go, relay/writer/file_test.go, relay/writer/file_util.go, syncer/ddl_exec_info.go, syncer/ddl_exec_info_test.go, syncer/dml.go, syncer/util.go
use `staticcheck` tool (`staticcheck $(go list ./...)`) finds some minor warnings
1. most changes are syntax refine
2. `bytes.Equal()` is faster than `bytes.Compare() != 0`
```
goos: linux
goarch: amd64
BenchmarkCompare-2      300000000                6.01 ns/op
BenchmarkEqual-2        300000000                5.21 ns/op
PASS
ok      command-line-arguments  4.492s
```
Tests 
- Unit test
=> *: some static check fix

cmd/dm-worker/main.go
In [TOOL-1417](https://internal.pingcap.net/jira/browse/TOOL-1417), a
user complained that dm-worker failed to start but output no logs.
This is a bug introduced in #195, which use the logger before it's
initialized.
Use fmt.Printf instead.
Tests 
- Manual test
Run dm-worker with some invalid flag and make sure error messages are
printed.
Code changes
Side effects
=> dm-worker: Should use fmt.Printf instead of the uninitialized logger

dm/pb/dmmaster.pb.go, dm/pb/dmworker.pb.go, dm/pb/tracer.pb.go, dm/pb/tracer_base.pb.go, dm/pb/tracer_syncer.pb.go, dm/proto/dmworker.proto, dm/worker/server.go
Fix
[Tool-920](https://internal.pingcap.net/jira/browse/TOOL-920?src=confmacro)
Include `sourceID` in worker status responses.
Add the `sourceID` field to `QueryStatusResponse` and set it in
`queryStatus`
Tests 
Code changes
Side effects
=> dm/worker: Include SourceID in QueryStatusResponse

cmd/dm-worker/main.go, go.mod, go.sum, syncer/syncer_test.go, tests/safe_mode/conf/dm-task.yaml, tests/sequence_safe_mode/conf/dm-task.yaml
1. Add syncer sharding test to increase syncer test coverage
2. Update tidb-tool go module
3. Update safe_mode/sequence_safe_mode mydumper config in integration test
Add TestSharding function to test
Simulate two tables(t1,t2) in one dm-worker syncer to one target table
```t1 insert -> t2 insert -> t1 add column -> t2 insert -> t2 add column -> t1, t2 insert (new schema)```
and check mock result as wish
Tests 
- Unit test
=> Add syncer sharding test

CHANGELOG.md, syncer/syncer_test.go
issue: https://github.com/pingcap/dm/issues/70
detect casuality conflict and generate flush job test case
refine test, run some sqls which will trigger casuality 
Tests 
- Unit test
=> syncer: refine syncer test to trigger casuality

dm/tracer/http_handler.go, dm/tracer/http_handler_test.go, dm/tracer/http_status.go, dm/tracer/store.go, syncer/dml.go, syncer/syncer.go, syncer/syncer_test.go, tests/_dmctl_tools/check_safe_mode.go, tests/safe_mode/run.sh, tests/sequence_safe_mode/run.sh
*: Use insert for non safe-mode instead of replace
check safe-mode as update event, and use insert for non safe-mode instead of replace
Tests 
Code changes
Side effects
=> *: Use insert for non safe-mode instead of replace

dm/worker/worker.go
I found DM-worker sometimes faild to start if start-stop-start in sequence frequently, with levelDB error `LOCK: Resource temporarily unavailable`, it is always a good habit to release resource in exit function. 
close levelDB when `worker.Worker` closes.
Tests 
=> worker: close kv db when worker exits

pkg/streamer/reader.go, pkg/streamer/reader_test.go, syncer/syncer.go
Combine two Syncer members (`Syncer.syncer` and `Syncer.localReader`) into one variable (streamerProducer), base on two reasons:
1. Obviously `Syncer.syncer` and `Syncer.localReader` has same ability to generate stream which can generate events, And Syncer only need one not two at any time
2.  And after put them in one interface, it's easy for any implementations who implement StreamerProducer and Stream interfaces to take place of `Syncer.streamerProducer`, such as a mock test
Combine two Syncer members into one `streamerProducer`
Tests 
- Unit test
=> Combine syncer localReader into one interface

dm/worker/server_test.go, dm/worker/worker.go, dm/worker/worker_test.go
Fix a panic bug in dm task hander 
We can reproduce the panic with steps as follows:
1. setup a DM cluster, start a task
2. stop one of DM-worker, delete the dm_worker_meta  directory of this node
3. start this DM-worker, send `stop-task`, `pause-task` or `resume-task` from DM-master
If task meta is not stored in DM-worker's memory when we want to use it, log a warning message instead of using it. 
Tests 
- Unit test
Code changes
Side effects
=> worker: fix panic in handle task

dm/worker/subtask.go, tests/initial_unit/run.sh
A subtask can transform from `paused` to `running` state by `resume-task`, but we should not allow a subtask to `resume` in running state.
When we create a new subtask, its state is `New`, and then we call `Init` of this task to initialize all the units of it, then the `initialized` flag will be set to true.
In the old logic, assuming there is a subtask with mode `all` and is running under sync unit, we stop it and restart from task config. Then it will not correctly set the `initialized` value.
Use a variable to record where subtask initialization is successful.
Tests 
- Unit test
Code changes
Side effects
=> worker: fix subtask initialized state

syncer/db_test.go, syncer/ddl_test.go, syncer/syncer.go, syncer/syncer_test.go
1. Remove db operations in syncer test
2. Move reset operations in Process() outside
1. Remove db operations in syncer test
- Remove `db *sql.DB` `syncer *BInlogSyncer` in TestSyncer Suite and use mock instead.
- Split TestDB Suite from TestSyncer Suite, move `TestTimeZone`  into TestDB Suite. 
- only `TestGeneratedColumn` is still need real db to generate binlog events, because mockEventGenerator doesn't support generate events include some field like `json`. 
2. Move reset operations in Process() outside
- Syncer `Process()` often starts in other goroutine but reset operations need to be done in main goroutine before execute next instruction. I think move reset operations outside is better than waiting some seconds.
- After moved the reset operations outside, we must ensure `reset()` …
=> syncer: release mysql dependencies in syncer test (2)

pkg/baseconn/conn.go, syncer/db.go, syncer/db_test.go, syncer/syncer.go, syncer/syncer_test.go
for example:
execute ddl in upstream `alter table t1 add column a int, add column b int`, syncer will split it to two ddls:
ddl1 `alter table t1 add column a int`
ddl2 `alter table t1 add column b int`
syncer will execute sqls ddl1 and ddl2 together, and if execute ddl1 meet error and this error can be ignored, will skip execute ddl2. 
fix it, judge whether error can be ignored when execute sql, if can ignore will continue execute next sql.
Tests 
- Unit test
Code changes
=> syncer: ignore error may skip execute some ddls

tests/dmctl_basic/conf/diff_config.toml, tests/print_status/conf/diff_config.toml, tests/sequence_sharding/conf/diff_config.toml, tests/sharding/conf/diff_config.toml
After this pr https://github.com/pingcap/tidb-tools/pull/248, `remove-columns` is removed from `sync_diff_inspector`, let's make test cases compatible with the latest `sync_diff_inspector`
Replace `remove-columns` with `ignore-columns` in `sync_diff_inspector` config in test cases
NOTE:
- to pass the CI for this pr, we should change the dm_ghpr_test test script, use the latest download link for `syncer_diff_inspector`, http://download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.tar.gz
- after this pr is merged, we can change the download link permanently, both in dm_ghpr_test and test_dm_master
Tests 
Code changes
Side effects
=> tests: fix sync diff config in test cases

pkg/retry/errors.go
some tidb error can be resolved  by retry, add some retryable error type
add some error
ErrQueryInterrupted: query execution was interrupted by user
ErrWriteConflictInTiDB: commit meets an write conflict error
ErrWriteConflict:  similar with ErrWriteConflictInTiDB
ErrTableLocked:  the table was locked by other session, can retry success when other session release the lock.
=> pkg/retry: add some retryable error

dm/worker/worker.go
DM-worker must be shutdown gracefully after receiving `kill` or `kill -hup`, but some condition exists lock acquire starvation and `worker.Close()` will not end.
one scenario is as follows:
`worker.Close()`, w acquired a lock -> `w.relayPurger.Close()` -> relayPurger.wg.Wait(), wait relayPurger.run ends
`relayPurger.run` -> ticker trigger, tryPurge -> interceptor, aka `*Worker` call `ForbidPurge()`, which will try to acquire `worker.RLock`
we can wrap Mutex with some atomic operation to achieve `TryLock` feature, but I think it is over-optimization for this scenario.
remove lock protection in `ForbidPurge`
Tests 
- Unit test
Code changes
Side effects
=> dm-worker: fix lock acquire starvation

dm/worker/status.go
Fix panic
```
panic: interface conversion: interface {} is *pb.LoadStatus, not *pb.DumpStatus
goroutine 176025 [running]:
github.com/pingcap/dm/dm/worker.(*Worker).Status(0xc000108000, 0x0, 0x0, 0x2, 0x2, 0xc0003202c0)
/home/jenkins/workspace/build_dm_master/go/src/github.com/pingcap/dm/dm/worker/status.go:101 +0xb1d
github.com/pingcap/dm/dm/worker.(*Worker).QueryStatus(0xc000108000, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/jenkins/workspace/build_dm_master/go/src/github.com/pingcap/dm/dm/worker/worker.go:312 +0xf5
github.com/pingcap/dm/dm/worker.(*Server).QueryStatus(0xc000554040, 0x18dee00, 0xc00556e6c0, 0xc00bd48170, 0xc000554040, 0xc00556e6c0, 0xc0002a3bd0)
/home/jenkins/workspace/build_dm_master/go/src/github.com/pingcap/dm/dm/worker/server.go:244 +0x2a0 …
```
=> dm-worker: fix panic in query status

dm/worker/status.go
cherry-pick #274 into release-1.0
=> dm-worker: fix panic in query status (#274)

checker/checker.go
keep the original database error in the error message for checker.
use `Error.Delegate` to replace `Error.Generate`.
Tests 
1. set a wrong password for DM-worker
2. `start-task`
the original error message is 
```
[code=26002:class=dm-master:scope=upstream:level=high] fail to initial checker: failed to open DSN root:***@127.0.0.1:3306\ngithub.com/pingcap/dm/pkg/terror.(*Error).Generate\n\t/Users/zhangxc/gopath/src/github.com/pingcap/dm/pkg/terror/terror.go:232\ngithub.com/pingcap/dm/checker.(*Checker).Init\n\t/Users/zhangxc/gopath/src/github.com/pingcap/dm/checker/checker.go:129\ngithub.com/pingcap/dm/checker.CheckSyncConfig\n\t/Users/zhangxc/gopath/src/github.com/pingcap/dm/checker/cmd.go:50\ngithub.com/pingcap/dm/dm/master.(*Server).gene …
```
=> checker: keep the original database error in the error message

checker/checker.go
**cherry-pick #276**
keep the original database error in the error message for checker.
use `Error.Delegate` to replace `Error.Generate`.
Tests 
1. set a wrong password for DM-worker
2. `start-task`
the original error message is 
```
[code=26002:class=dm-master:scope=upstream:level=high] fail to initial checker: failed to open DSN root:***@127.0.0.1:3306\ngithub.com/pingcap/dm/pkg/terror.(*Error).Generate\n\t/Users/zhangxc/gopath/src/github.com/pingcap/dm/pkg/terror/terror.go:232\ngithub.com/pingcap/dm/checker.(*Checker).Init\n\t/Users/zhangxc/gopath/src/github.com/pingcap/dm/checker/checker.go:129\ngithub.com/pingcap/dm/checker.CheckSyncConfig\n\t/Users/zhangxc/gopath/src/github.com/pingcap/dm/checker/cmd.go:50\ngithub.com/pingcap/dm/dm/ …
```
=> checker: keep the original database error in the error message (#276)

loader/db.go, pkg/baseconn/conn.go, pkg/baseconn/conn_test.go, syncer/checkpoint_test.go, syncer/db.go, syncer/syncer_test.go
currently we use a single `sql.DB` connection pool for multiple concurrent executors in single DM-worker, each time one a txn is committed, the connection will be tried to put back to the idle connection pool. Too small idle connection pool size will lead to rejection of the put-back and database too many connections re-create.
set database MaxIdleConns according to worker-count
Tests 
- Unit test
Code changes
Side effects
- Fix a bug that may cause database connection re-establish too frequent
=> conn: add max idle conn config

dm/ctl/master/check_task.go, dm/ctl/master/pause_task.go, dm/ctl/master/query_error.go, dm/ctl/master/query_status.go, dm/ctl/master/resume_task.go, dm/ctl/master/show_ddl_locks.go, dm/ctl/master/sql_inject.go, dm/ctl/master/start_task.go, dm/ctl/master/stop_task.go, dm/ctl/master/update_masterconfig.go, dm/ctl/master/update_relay.go, dm/ctl/master/update_task.go, tests/dmctl_advance/check_list/query_error.sh, tests/dmctl_basic/check_list/check_task.sh, tests/dmctl_basic/check_list/pause_task.sh, tests/dmctl_basic/check_list/query_status.sh, tests/dmctl_basic/check_list/resume_task.sh, tests/dmctl_basic/check_list/show_ddl_locks.sh, tests/dmctl_basic/check_list/start_task.sh, tests/dmctl_basic/check_list/stop_task.sh, tests/dmctl_basic/check_list/update_master_config.sh, tests/dmctl_basic/check_list/update_relay.sh, tests/dmctl_basic/check_list/update_task.sh
refine some name in the output of dmctl to match https://github.com/pingcap/docs-cn/pull/1878
- rename `dm-master` to `DM-master`
- rename `task_name` to `task-name`
- rename `config_file` to `config-file`
Tests 
- Unit test
- run commands in dmctl, observe the output
=> *: refine dmctl output for `DM-master`, `task-name` and `config-file`

syncer/syncer.go, syncer/syncer_test.go
in-memory job counter counts on both added jobs and finished jobs.
count finished jobs only.
Tests 
- Unit test
Code changes
Side effects
=> syncer: fix in-memory tps count

syncer/syncer.go, syncer/syncer_test.go
cherry-pick #286 into release-1.0
=> syncer: fix in-memory tps count (#286)

syncer/syncer.go
Optimize sync function 
Split sync DDL from `sync()` because sync DDL and sync DML don't have to many common logic.
Split them to make the code clear.
Tests 
- Unit test
- No code
Code changes
Side effects
=> dm-worker: split DDL sync from sync function

dm/ctl/master/check_task.go, dm/ctl/master/pause_task.go, dm/ctl/master/query_error.go, dm/ctl/master/query_status.go, dm/ctl/master/resume_task.go, dm/ctl/master/show_ddl_locks.go, dm/ctl/master/sql_inject.go, dm/ctl/master/start_task.go, dm/ctl/master/stop_task.go, dm/ctl/master/update_masterconfig.go, dm/ctl/master/update_relay.go, dm/ctl/master/update_task.go, tests/dmctl_advance/check_list/query_error.sh, tests/dmctl_basic/check_list/check_task.sh, tests/dmctl_basic/check_list/pause_task.sh, tests/dmctl_basic/check_list/query_status.sh, tests/dmctl_basic/check_list/resume_task.sh, tests/dmctl_basic/check_list/show_ddl_locks.sh, tests/dmctl_basic/check_list/start_task.sh, tests/dmctl_basic/check_list/stop_task.sh, tests/dmctl_basic/check_list/update_master_config.sh, tests/dmctl_basic/check_list/update_relay.sh, tests/dmctl_basic/check_list/update_task.sh
cherry-pick #291 
refine some name in the output of dmctl to match https://github.com/pingcap/docs-cn/pull/1878
- rename `dm-master` to `DM-master`
- rename `task_name` to `task-name`
- rename `config_file` to `config-file`
Tests 
- Unit test
- run commands in dmctl, observe the output
=> *: refine dmctl output for `DM-master`, `task-name` and `config-file` (#291)

dm/ctl/ctl.go, dm/ctl/master/break_ddl_lock.go, dm/ctl/master/check_task.go, dm/ctl/master/migrate_relay.go, dm/ctl/master/pause_relay.go, dm/ctl/master/pause_task.go, dm/ctl/master/purge_relay.go, dm/ctl/master/query_error.go, dm/ctl/master/query_status.go, dm/ctl/master/resume_relay.go, dm/ctl/master/resume_task.go, dm/ctl/master/sql_inject.go, dm/ctl/master/sql_replace.go, dm/ctl/master/sql_skip.go, dm/ctl/master/start_task.go, dm/ctl/master/stop_task.go, dm/ctl/master/switch_relay_master.go, dm/ctl/master/unlock_ddl_lock.go, dm/ctl/master/update_masterconfig.go, dm/ctl/master/update_relay.go, dm/ctl/master/update_task.go, tests/dmctl_advance/check_list/break_ddl_lock.sh, tests/dmctl_advance/check_list/switch_relay_master.sh, tests/dmctl_basic/check_list/pause_relay.sh, tests/dmctl_basic/check_list/purge_relay.sh, tests/dmctl_basic/check_list/resume_relay.sh, tests/dmctl_basic/check_list/update_relay.sh
cherry-pick #296 
refine dmctl comands' usage text
refine usage suggestion from I18N team in https://github.com/pingcap/docs-cn/pull/1878.
Tests 
1. run dmctl
2. observe the output of usage
=> dmctl: refine commands' usage text (#296)

dm/worker/worker.go, dm/worker/worker_test.go
```golang
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x53b07e]
goroutine 47 [running]:
context.WithDeadline(0x0, 0x0, 0xbf5be448e73dc52d, 0x463dd73766, 0x2ad5a60, 0x0, 0x0, 0x0)
/usr/local/go/src/context/context.go:384 +0x4e
context.WithTimeout(0x0, 0x0, 0x45d964b800, 0xc001974200, 0x2, 0x2)
/usr/local/go/src/context/context.go:451 +0x6b
github.com/pingcap/dm/dm/worker.(*SubTask).unitTransWaitCondition(0xc000372e40, 0x0, 0x0)
/home/jenkins/workspace/build_dm_master/go/src/github.com/pingcap/dm/dm/worker/subtask.go:627 +0x3ca
github.com/pingcap/dm/dm/worker.(*SubTask).run(0xc000372e40)
/home/jenkins/workspace/build_dm_master/go/src/github.com/pingcap/dm/dm/worker/subtask.go:182 +0x5c
github.com/pingcap/dm/dm/worker.(*SubTask).fetchResult(0xc000372e40, 0xc0004a7560) …
```
=> worker: fix potential panic when restoring subtask from meta

dm/master/server.go, dm/master/server_test.go, tests/start_task/conf/dm-master.toml, tests/start_task/run.sh
The previous version of DM-master always fetches all DM-workers' config when starting a task.
When having any un-accessible DM-worker, then we can't start any task.
Change to only fetches necessary DM-workers' config
Tests 
- Unit test
- start task with un-accessible DM-worker
=> master: only fetch necessary DM-worker's config

dm/worker/task_checker.go, pkg/retry/errors.go, syncer/db.go
cherry-pick #317 into release-1.0
=> syncer: fast fail on some error in ddl execution (#317)

dm/worker/config.go, dm/worker/config_test.go, pkg/utils/db.go, tests/all_mode/conf/dm-worker1.toml, tests/all_mode/conf/dm-worker2.toml, tests/compatibility/conf/dm-worker1.toml, tests/compatibility/conf/dm-worker2.toml, tests/dmctl_basic/conf/dm-worker1.toml, tests/dmctl_basic/conf/dm-worker2.toml, tests/http_apis/conf/dm-worker1.toml, tests/incremental_mode/conf/dm-worker1.toml, tests/incremental_mode/conf/dm-worker2.toml, tests/initial_unit/conf/dm-worker1.toml, tests/load_interrupt/conf/dm-worker1.toml, tests/load_interrupt/conf/dm-worker2.toml, tests/online_ddl/conf/dm-worker1.toml, tests/online_ddl/conf/dm-worker2.toml, tests/print_status/conf/dm-worker1.toml, tests/relay_interrupt/conf/dm-worker1.toml, tests/safe_mode/conf/dm-worker1.toml, tests/safe_mode/conf/dm-worker2.toml, tests/sequence_safe_mode/conf/dm-worker1.toml, tests/sequence_safe_mode/conf/dm-worker2.toml, tests/sequence_sharding/conf/dm-worker1.toml, tests/sequence_sharding/conf/dm-worker2.toml, tests/sharding/conf/dm-worker1.toml, tests/sharding/conf/dm-worker2.toml, tests/start_task/conf/dm-worker1.toml
cherry-pick #323 to release-1.0
---
[TOOL-1166](https://internal.pingcap.net/jira/browse/TOOL-1166)
Now, we need to set flavor for DM-worker manually, but it may be set incorrectly.
use `dbutil.ShowVersion` and `check.IsMariaDB` from [tidb-tools](https://github.com/pingcap/tidb-tools) to detect upstream MySQL/MariaDB server type and set flavor automatically.
Tests 
- Unit test
=> worker: generate index flavor automatically by querying version info from DB (#323)

pkg/retry/errors.go, syncer/db.go, syncer/error_test.go, tests/load_interrupt/run.sh
`1105` means an unknown error in MySQL/TiDB. some of these errors are retryable, but some are not (like `error="Error 1105: statement count 5001 exceeds the transaction limitation`).
only retry for retryable errors, now including:
- `Information schema is out of date`
- `Information schema is changed`
Tests 
- Unit test
=> *: only retry for special message with 1105

CHANGELOG.md
- add release notes for v1.0.2
- add release notes for v1.0.2
Tests 
- No code
=> CHANGELOG: add release notes for v1.0.2

dm/dm-ansible/roles/dm-worker/templates/dm-worker.toml.j2
server-id, flavor, relay-binlog-name and relay-binlog-gtid is not necessary any more, so user may not set in inventory.ini when use ansible to deploy, but now it will return error "AnsibleUndefinedVariable: 'server_id' is undefined"
manual test
don't add config in config file if not setted in inventory.ini
=> dm-ansible: don't add config in config file if not setted in inventory.ini

dm/ctl/ctl.go
1. Every time we run command in dmctl with -w arg the argument worker will be accumulated which doesn't match our expectations.
2. After we set flag to rootCmd, the value will be kept. Although we don't specify this arg in the next time. it still has a value.
1. Clear workers array every time before we run a command.
2. New rootCmd every time before we run a command. I tried `rootCmd.ResetFlags()` but it will remove all flags and we can not specify any arg any more. Is there any better solution?
Tests 
- Unit test
1. ![image](https://user-images.githubusercontent.com/21104942/69206449-ab42e580-0b87-11ea-8ce7-e2b25ca9dacb.png)
2. ![image](https://user-images.githubusercontent.com/21104942/69209005-9c146580-0b90-11ea-940e …
=> dmctl/:Clear workers cache before we run a command

go.mod, go.sum, tests/all_mode/data/db1.increment.sql
in golang v1.13, the _Decimal decompose interface_ is introduced, see:
- https://github.com/golang/go/issues/30870
- https://github.com/golang/go/commit/683ffe09f66f0834baf039deeabe16eec6b09daa
in [shopspring/decimal@75bb2cb](https://github.com/shopspring/decimal/commit/75bb2cb98e710b1a43ff4611ebdbbbfa3d3314c3), it implements the _Decimal decompose interface_.
when executing a statement with decimal type columns, a possible execution path is:
1. https://github.com/golang/go/blob/cc8838d645/src/database/sql/sql.go#L2275
2. https://github.com/golang/go/blob/cc8838d645/src/database/sql/sql.go#L1515
3. https://github.com/golang/go/blob/cc8838d645/src/database/sql/convert.go#L177
4. https://github.com/go-sql-driver/mysql/blob/v1.4.1/connection_go18.go#L196
5. …
=> *: fix `cannot convert type: decimal.Decimal`

Makefile, pkg/streamer/file_test.go, pkg/streamer/hub_test.go, pkg/streamer/reader_test.go, pkg/utils/storage.go, pkg/utils/storage_unix.go, pkg/utils/storage_windows.go, relay/writer/file_test.go, relay/writer/file_util_test.go
Supports running (not necessarily passing) `make unit_test` on Windows (because etcd doesn't work on WSL).
DM only has one non-Windows dependency which is computing the free space. Generalized this to work on Windows too.
Also, relaxed some tests which rely on Unix-specific error messages.
Tests 
- Unit test
Code changes
Side effects
=> *: support running unit test on Windows

loader/db.go, loader/loader.go, pkg/conn/baseconn.go, pkg/log/log.go, pkg/log/log_test.go, pkg/utils/util.go, syncer/db.go, syncer/syncer.go, syncer/warning.go
cherry-pick #355 and #381 to release-1.0
---
When an error occurs and the context in loader/syncer is canceled, the normally running sql will be canceled and return a `context.Canceled` error, which will confuse the users.
Filter all the `context.Canceled` in loader/syncer. Don't return error and don't print log.
Tests 
- Unit test
=> loader/syncer: filter context cancel error while executing sqls (#355)

pkg/utils/util.go, syncer/filter_test.go, tests/all_mode/data/db1.increment.sql
TiDB supports `ALTER DATABASE` now, remove it in DM default filter
remove `alter database` from `builtInSkipDDLs`
Tests 
- Unit test
Code changes
Side effects
=> pkg: support to sync alter database DDL

go.mod, go.sum, loader/db.go, pkg/retry/errors.go, pkg/retry/strategy_test.go, syncer/db.go, syncer/error_test.go
replace `IsRetryableError` with the one in tidb-tools repo
- update tidb-tools mod
- replace `IsRetryableError` usage
Tests 
- Unit test
Code changes
=> *: use `IsRetryableError` in tidb-tools

pkg/log/log.go
Without the `AddCallerSkip(1)` all logs going through `ErrorFilterContextCanceled()` will show the source as `log.go:93`.
Tests 
* Check the log after applying the patch
Code changes
Side effects
=> log: skip 1 caller in ErrorFilterContextCanceled()

syncer/syncer.go
in #355, ignore canceled errors for executing SQLs is introduced.
but miss to ignore the canceled errors for executing DMLs.
check `!utils.IsContextCanceledError(err)` before `s.runFatalChan <- unit.NewProcessError(errType, err)` for executing DMLs as we did for DDL.
Tests 
- Unit test
- hack the code for executing DMLs and return an error in one goroutine
- obverse the log and result of `query-status` for `context canceled` error
- Need to be included in the release note (with #355)
=> syncer: fix ignore canceled error

dm/dm-ansible/rolling_update_monitor.yml
Fix the missing var "dm_worker_instances "  for rolling_update_monitor
Add the var " dm_worker_instances " with the same logical as start.yml
=>  Fix the missing var dm_worker_instances for rolling_update_monitor

Makefile, dm/worker/worker_test.go
- when multi test cases in different test suite write data in the upstream, the binlog may become out of order.
- run all unit test cases in one job in CI is a  little slow.
- split unit tests according to pkg (in _Makefile_), and now split them into:
- unit_test_relay
- unit_test_syncer
- unit_test_pkg_binlog
- unit_test_others
- update jenkins pipeline
Tests 
=> *: split unit test according to upstream MySQL

Makefile, dm/worker/worker_test.go, pkg/streamer/file_test.go, pkg/streamer/hub_test.go, pkg/streamer/reader_test.go, pkg/utils/storage.go, pkg/utils/storage_unix.go, pkg/utils/storage_windows.go, relay/writer/file_test.go, relay/writer/file_util_test.go
split unit test according to upstream MySQL
cherry pick #378 and #416 (both of them modify the same line in _Makefile_).
Tests 
- Unit test
=> *: cherry pick #378 and #416

dm/portal/api.go, dm/portal/api_test.go
fix a bug, when DoTables is empty will generate "-T " for Mydumper, which is invalid.
fix it
Tests 
- Manual test
- Unit test
=> dm-portal: don't generate table list for mydumper  if DoTables is empty

.gitignore, Makefile, dm/pb/dmmaster.pb.go, dm/pb/dmmaster.pb.gw.go, dm/pb/dmworker.pb.go, dm/pb/tracer.pb.go, dm/pb/tracer_base.pb.go, dm/pb/tracer_syncer.pb.go, generate-dm.sh, go.mod, go.sum, retool-install.sh, tests/generate-mock.sh, tools.json, tools/tools.go
see #445 
- use [retool](https://github.com/twitchtv/retool) to track executables written in Go
- use _go.mod_ to track source code dependencies (including _retool_)
- re-generate proto file with dependencies in _go.mod_
Tests 
- Unit test
=> track tool dependencies in the repo

dm/portal/api_test.go, dm/worker/worker_test.go, syncer/streamer_controller.go
1. `GetEvent` may cost too many time, and will lock the `StreamerController`, need refine it
2. both `Start` and `Close` have lock, but when `Start` failed will call the `Close` function, need fix the dead lock
fix the lock
Tests 
- Manual test 
=> syncer: fix lock in streamer controller

dm/worker/worker_test.go, syncer/streamer_controller.go
1. GetEvent may cost too many time, and will lock the StreamerController, need refine it
2. both Start and Close have lock, but when Start failed will call the Close function, need fix the dead lock
cherry-pick from #470 and resolve conflicts
Tests 
- Manual test
=> syncer: fix lock in streamer controller(#470)

cmd/dm-syncer/config.go, cmd/dm-syncer/main.go, dm/config/subtask.go, dm/config/subtask_test.go, dm/config/task.go, dm/worker/meta.go, dm/worker/meta_test.go
1. don't decrypt password, will connect to database failed
2.  log is not initial, need to use `fmt` to print parse error
fix these two problems
Tests 
- Manual test
=> dm-syncer: minor fix on password && print parse error

dm/portal/frontend/package.json, dm/portal/frontend/src/App.tsx, dm/portal/frontend/src/components/BinlogFilterModal.tsx, dm/portal/frontend/src/components/InstancesStep.tsx, dm/portal/frontend/src/components/Layout.tsx, dm/portal/frontend/src/components/MigrateStep.tsx, dm/portal/frontend/src/components/NamingStep.tsx, dm/portal/frontend/src/components/StartStep.tsx, dm/portal/frontend/src/components/UploadStep.tsx, dm/portal/frontend/src/locales/en-US.ts, dm/portal/frontend/src/locales/index.ts, dm/portal/frontend/src/locales/zh-CN.ts, dm/portal/frontend/yarn.lock
Add i18n support for DM Portal, satisfy #475 feature request.
You can choose which language want to use.
=> dm-portal: add i18n support

dm/master/config.go, dm/master/config_test.go, dm/worker/config.go, dm/worker/config_test.go
export `advertise-addr` to make DM easier to use in cloud.
export `advertise-addr` as the command arg; use `master-addr`
Tests 
- Unit test
=> *: export `advertise-addr` as the command arg; use `master-addr`

dm/master/etcd.go, dm/master/etcd_test.go, dm/master/server.go
fix #507 
see comments in _dm/master/etcd.go_ from L61 to L68.
Tests 
- Unit test
=> dm-master: fix DM-master can not exit when starting timeout

dm/ctl/master/query_status.go
UCP #505 
Add `--more` index for `query-status` command to get full task information.
It will check `--more` index for `query-status` command. If this index exist, it will print full tasks information.
Tests 
- No code
=> dm-ctl/: add `--more` index for `query-status` command to get full task information

pkg/election/election.go
when master retire from leader, not set `oldLeaderInfo = ""`, and if this master become leader again, will contine at L273 and not notify the master 
set `oldLeaderInfo = ""` after retire from leader
=> election: reset oldLeaderID after retire from leader

_utils/terror_gen/errors_release.txt, go.mod, go.sum, pkg/binlog/event/common.go, pkg/binlog/event/common_test.go, pkg/binlog/event/event.go, pkg/binlog/event/event_test.go, pkg/binlog/event/generator_test.go, pkg/binlog/event/helper.go, pkg/binlog/event/helper_test.go, pkg/terror/error_list.go, relay/relay.go, relay/relay_test.go, relay/writer/file_util.go
fix #443 , this should be release under v1.0.4.
- support recover relay log file with a subset of metadata
- check whether the metadata is a subset of the relay log file
- also update `go-mysql` to fix `GTIDSet.Equal`.
Tests 
- Unit test
Code changes
Side effects
=> *: support recover relay log file with a subset of metadata

dm/ctl/master/query_status.go
cherry-pick #523
Add `--more` index for `query-status` command to get full task information.
It will check `--more` index for `query-status` command. If this index exist, it will print full tasks information.
Tests 
- No code
=> dm-ctl/: add `--more` index for `query-status` command to get full task information(#523) 

_utils/terror_gen/errors_release.txt, go.mod, go.sum, pkg/binlog/event/common.go, pkg/binlog/event/common_test.go, pkg/binlog/event/event.go, pkg/binlog/event/event_test.go, pkg/binlog/event/generator_test.go, pkg/binlog/event/helper.go, pkg/binlog/event/helper_test.go, pkg/terror/error_list.go, relay/relay.go, relay/relay_test.go, relay/writer/file_util.go
cherry-pick #530 to release-1.0
---
fix #443 , this should be release under v1.0.4.
- support recover relay log file with a subset of metadata
- check whether the metadata is a subset of the relay log file
- also update `go-mysql` to fix `GTIDSet.Equal`.
Tests 
- Unit test
Code changes
Side effects
=> *: support recover relay log file with a subset of metadata (#530)

pkg/utils/db.go, pkg/utils/db_test.go
fix #536 
use `strconv.ParseUint` instead of `strconv.ParseInt` to parse `server_id`.
Tests 
- Unit test
=> utils: fix `value out of range` for getting `server_id`

CHANGELOG.md
- add release notes for v1.0.4
- add release notes for v1.0.4
Tests 
- No code
=> CHANGELOG: add release notes for v1.0.4

loader/checkpoint.go, loader/loader.go
fix #553 
- for load unit, only one `RemoteCheckPoint` exists.
- for `RemoteCheckPoint`, only one `DBConn` exist.
- but `DBConn` is not concurrency-safe.
so, some checkpoint operations like `Init` may cause a problem.
add `sync.Mutex` to protect operations for `DBConn`.
Tests 
- Unit test
Side effects
=> loader: fix concurrent usage of checkpoint's DBconn.

cmd/dm-worker/main.go, dm/master/scheduler/scheduler_test.go, dm/worker/join.go, tests/ha_master/run.sh
https://github.com/pingcap/dm/issues/560
When worker dials an offline master, it will returns error directly and stop the worker process.
1. add `WithBlock` option for grpc dial to avoid dialing an offline master.
2. don't return error immediately when dialed master is offline. Try to dial other endpoint in `cfg.Join`.
3. do the register request in the loop to avoid dialing an online master which is blocked from other dm-masters.
Tests 
- Unit test
=> worker/: don't quit worker immediately when dialed master is offline

dm/dm-ansible/scripts/dm.json, loader/loader.go, loader/metrics.go
fix #459 
* modify this metrics to gaugeVec:
* dataFileCountor => dataFileGauge
* tableCountor => tableGauge
* dataSizeCountor => dataSizeGauge
* modify dm/dm-ansible/scripts/dm.json related PromQL expressions
* modify related code for metrics
=> fix: reset some metrics when loader resume 

_utils/terror_gen/errors_release.txt, dm/master/scheduler/scheduler.go, dm/master/scheduler/scheduler_test.go, dm/master/shardddl/pessimist.go, dm/master/shardddl/pessimist_test.go, pkg/terror/error_list.go
https://github.com/pingcap/dm/issues/561
1. set etcdClient to component at the beginning initialization
2. use `p.mu.Lock` for `Pessimist.UnlockLock` to avoid concurrency.
3. add stronger UT in scheduler and pessimist.
Tests 
- Unit test
=> ha: set etcdClient to component at the beginning initialization

dm/worker/server.go
We append pointer of loop variables, which can't represent the actual value.
Append pointers of subtask config's copy.
Tests 
- Unit test
=> worker/: fix subtask config pointer usage

syncer/dml.go, syncer/syncer.go
disable conflict between different tables.
make table name as the prefix of the key
Tests 
- Unit test
Side effects
=> syncer: make table name as the prefix of the key

dm/dm-ansible/scripts/dm.json, loader/db.go, loader/metrics.go, pkg/conn/baseconn.go, pkg/conn/baseconn_test.go, pkg/conn/basedb_test.go, relay/metrics.go, syncer/db.go, syncer/error_test.go, syncer/metrics.go, syncer/syncer.go, syncer/syncer_test.go
add more metrics for binlog replication unit.
- add more metrics:
- `binlogReadDurationHistogram`
- `binlogEventSizeHistogram`
- `conflictDetectDurationHistogram`
- `queueSizeGauge`
- `stmtHistogram`
- refine batch handle (use `time.After` to replcate `time.Sleep`)
- update Grafana dashboard
Tests 
- Unit test
Code changes
Side effects
=> syncer: add more metrics; refine batch handle

dm/config/task.go, dm/dm-ansible/scripts/dm.json, loader/metrics.go, relay/metrics.go, syncer/checkpoint.go, syncer/dml.go, syncer/dml_test.go, syncer/metrics.go, syncer/syncer.go, syncer/syncer_test.go
- add metrics to diagnose perf issue
- improve perf
- add some metrics 
- increase job queue length
- use `strings.Builder` to replace some `fmt.Sprintf`
- `strings.Builder`/`bytes.Buffer` with `sync.Pool` doesn't achieve better perf
- remove some unnecessary slice create
- we can do more here, but it will make the code ugly and may not improve a lot, so I revert it
a sysbench workload in my laptop with the black hole downstream
`transform binlog event duration` (.90):
**before this PR: 143us --> after this PR: 72us**
`binlog event QPS`:
**before this PR: ~4k --> after this PR: ~6k**
**before this PR:**
**after this PR:**
Tests 
- Unit test
Code changes
Side effects
- …
=> syncer: improve performance

dm/config/subtask.go, dm/config/task.go, dm/dm-ansible/scripts/dm.json, syncer/checkpoint.go, syncer/dml.go, syncer/metrics.go, syncer/syncer.go, syncer/syncer_test.go
improve binlog replication performance in some cases.
- do not use `null` value as the concurrence dispatch key
- decrease  default value of `queue-size` from `5120` to `1024`
- add `checkpoint-flush-interval` config item
- update `binlogSkippedEventsTotal` to `skipBinlogDurationHistogram` to support observe duration and update the Grafana dashboard
Tests 
- Unit test
Code changes
Side effects
=> syncer: improve performance - part 2

dm/worker/metrics.go, dm/worker/subtask.go, loader/loader.go, loader/metrics.go, mydumper/metrics.go, mydumper/mydumper.go, pkg/conn/baseconn.go, pkg/conn/baseconn_test.go, pkg/metricsproxy/countervec.go, pkg/metricsproxy/countervec_test.go, pkg/metricsproxy/gaugevec.go, pkg/metricsproxy/gaugevec_test.go, pkg/metricsproxy/histogramvec.go, pkg/metricsproxy/histogramvec_test.go, pkg/metricsproxy/proxy.go, pkg/metricsproxy/proxy_test.go, pkg/metricsproxy/summaryvec.go, pkg/metricsproxy/summaryvec_test.go, pkg/streamer/reader_test.go, relay/metrics.go, syncer/metrics.go, syncer/syncer.go, tests/_dmctl_tools/check_master_online.go, tests/_dmctl_tools/check_worker_online.go, tests/initial_unit/run.sh, tests/relay_interrupt/run.sh, tests/start_task/run.sh
cherry-pick #575 and #578 to release-1.0 and resolve conflicts
cherry-pick #575 and #578 to release-1.0 and resolve conflicts
Tests 
- Unit test
Code changes
Side effects
=> cherry-pick #575 and #578 to release-1.0 and resolve conflicts

dm/worker/relay.go, dm/worker/subtask.go, dm/worker/subtask_test.go
cherry-pick #589
---
https://github.com/pingcap/dm/issues/576
When subtask is started, it will use `unitTransWaitCondition` to wait for relay log to catch up. But if this task is paused or stopped, we should quit as fast as we can instead of keeping waiting.
1. Use `st.currCtx` to control wait of `unitTransWaitCondition`.
2. Use parent context `st.ctx` and son context `st.currCtx` to make sure task can be shut down.
Tests 
- Unit test
=> worker/: fix worker stuck in unitTransWaitCondition(#589)

dm/dm-ansible/inventory.ini
update `dm_version` in DM-ansible's inventory.ini from `v1.0.4` to `v1.0.5`.
Tests 
- No code
=> ansible: release v1.0.5

pkg/binlog/common/replication.go, relay/relay.go, syncer/syncer.go
when enabling retry, go-mysql will [retry sync](https://github.com/siddontang/go-mysql/blob/3731d5147201d61e212e7fbd0c83ea14cb6ef0b9/replication/binlogsyncer.go#L577) from the previous GTID set in GTID mode, 
which may get duplicate binlog event after retry success. 
so just disable retry, and the task will exit with error, then auto-resume by DM itself.
Tests 
- Manual test
=> sync unit: disable retry for binlog syncer

go.mod, go.sum, mydumper/mydumper.go
update tidb-tools to solve table name changing after applyOn black-white-list, details at pingcap/tidb-tools#342
change tidb-tools to latest version
Tests 
- Unit test
=> update tools dependency

mydumper/mydumper.go
mydumper exits log is very confusing now
distinguish exits normally with exits with error by different logs.
Tests 
- Unit test
=> refine mydumper exits error log

dm/portal/frontend/src/components/NamingStep.tsx
dm-portal default name `test-task` will be judged as invalid name.
Change `test-task` to `test`
=> update dm-portal default name

dm/config/subtask.go, pkg/conn/basedb.go, tests/_utils/check_sync_diff, tests/all_mode/conf/dm-task.yaml, tests/all_mode/data/db1.prepare.sql, tests/all_mode/run.sh
cherry-pick #687 to release-1.0
add SessionConfig in TargetDB, set session variables in db.Apply.
Tests 
- Unit test
Code changes
=> config: support setting session variable (#687)

dm/worker/metrics.go, dm/worker/worker.go, syncer/metrics.go, syncer/syncer.go
Data race at collecting metrics. #672 
move cpu usage metrics to worker server level
Tests 
- Unit test
=> dm-worker: move cpu metrics to worker server level

dm/master/election.go, dm/master/election_test.go
fix wrong usage of failpoint in #695, which will cause unit test fail.
failpoint generate `ok` variable and overide outer `ok`
```
ok:=true
failpoint.Inject("", func(val failpoint.Value) {
ok=false
})
fmt.Println(ok) // ok still true
```
this pr rewrite the logic of failpoint in #695 
Tests 
- Unit test
=> fix wrong usage of failpoint in #695

checker/checker.go
#647 do not show the successful pre-check items if some items failed when starting task
remove successful result if fail
Tests 
- Unit test
run mysql with binlog disable
=> check-task: do not show successful pre-check items if fail

syncer/heartbeat.go, tests/README.md, tests/_utils/check_metric, tests/all_mode/run.sh
- #706
- #694 
- #707
- compare heartbeat schema and table as case-insensitive
- do not update replication lag metric if no valid slave ts exit
- use `UTC_TIMESTAMP(6)` to replace `UTC_TIMESTAMP()`
Tests 
- Unit test
=> syncer: refine heartbeat

syncer/heartbeat.go, tests/README.md, tests/_utils/check_metric, tests/all_mode/run.sh
cherry-pick #704 manually.
---
- #706
- #694 
- #707
- compare heartbeat schema and table as case-insensitive
- do not update replication lag metric if no valid slave ts exit
- use `UTC_TIMESTAMP(6)` to replace `UTC_TIMESTAMP()`
Tests 
- Unit test
=> syncer: refine heartbeat (#704)

checker/checker.go
cherry-pick #712 manually.
#647 
remove successful result if fail
Tests 
- Unit test
=> check-task: do not show successful pre-check items if fail(#712)

dm/worker/task_checker.go, pkg/retry/errors.go
cherry pick #732 
fix issue https://github.com/pingcap/dm/issues/709
add the error message to `UnsupportedDDLMsgs` list
=> don't resume task for `unsupported collation` error

dm/worker/task_checker.go, dm/worker/worker.go, pkg/retry/errors.go, syncer/sharding-meta/shardmeta.go, syncer/sharding_group.go, tests/sequence_sharding/conf/dm-task.yaml, tests/sequence_sharding/data/db1.increment3.sql, tests/sequence_sharding/data/db2.increment3.sql, tests/sequence_sharding/run.sh, tests/sharding/run.sh
manually cherrypick #722 
and fix #740.
- #719 
- #740 
reset shardmeta after start or resume task
Tests 
- Unit test
=> shardddl: fix resume conflict ddl.

syncer/checkpoint.go, syncer/checkpoint_test.go, syncer/syncer_test.go
manually cherrypick #758 
flush global checkpoint when first time flush checkpoint
=> checkpoint: cherrypick flush global checkpoint when first time flush checkpoint

dm/master/server_test.go, dm/master/source.toml, pkg/conn/basedb.go, tests/dmctl_basic/check_list/check_task.sh, tests/dmctl_basic/run.sh
close #766 
ping database when apply db config
Tests 
=> check_task: ping db when apply dbconfig

pkg/conn/basedb.go, tests/all_mode/run.sh, tests/dmctl_basic/check_list/check_task.sh, tests/dmctl_basic/run.sh
manually cherrypick #769 
ping database when apply db config
Tests 
=> check_task: cherrypick ping db when apply dbconfig

dm/worker/metrics.go, dm/worker/server.go, dm/worker/server_test.go, dm/worker/subtask.go, dm/worker/task_checker_test.go, dm/worker/worker.go, dm/worker/worker_test.go
part of #543 
add/modify two types of metrics:
- add label `source_id` for state of subtasks
- add counter of number of operate errors by (worker, error type), remove all `TODO: add better metrics`
Tests 
- pass original tests
Code changes
Side effects
=> worker: add metrics

cmd/dm-worker/main.go, dm/master/config.go
close #495 
- set error log level for embed etcd
- set error log level for global logger which currently only use by schemaTracker
Tests 
- Manually check the log
=> log: set log level for embed etcd and ddl tracker

dm/config/subtask.go, dm/config/task.go, loader/checkpoint.go, loader/loader.go, syncer/syncer.go, tests/all_mode/run.sh, tests/full_mode/run.sh, tests/import_goroutine_leak/run.sh, tests/incremental_mode/conf/dm-task.yaml, tests/load_interrupt/run.sh
manually cherry-pick #770 
Tests 
- Unit test
Code changes
Side effects
=> config, loader: auto-remove imported dump file (#770)

dm/master/scheduler/scheduler_test.go
reduce test fail for testScheduler.TestRestartScheduler: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/5753/pipeline
etcd's check and keep alive interval is `retryConnWait = 500 * time.Millisecond`, see https://github.com/etcd-io/etcd/blob/b28a6272b73359591fe22bac5ac8cae8afdbe0cc/clientv3/lease.go#L580. I guess it accounts for our 1 second TTL timeout
Tests 
- Unit test
Code changes
Side effects
=> test: increase TTL to improve stability

dm/master/config.go, dm/master/config_test.go
fix #819 
set `ACUrls` to `advertise-addr`.
Tests 
- run DM-master with `master-addr="0.0.0.0:8261` and `advertise-addr=127.0.0.1:8261`
- `list-member` and check `clientURLs` should be `http://127.0.0.1:8261`
=> dm-master: fix wrong clientURL

dm/master/metrics/metrics.go, dm/master/scheduler/scheduler.go, dm/master/scheduler/worker.go, dm/master/shardddl/optimist.go, dm/master/shardddl/pessimist.go, pkg/shardddl/optimism/lock.go, pkg/shardddl/pessimism/lock.go
part of #543
add metrics for optimistic shard DDL lock, and some renames because we call `metrics.ReportDDLPending` so don't repeat `...ToMetric`
Tests 
- Manual test (pause sequence_sharding_optimistic and check grafana)
Code changes
Side effects
=> *: add metrics for optimistic shard DDL lock

dm/dm-ansible/scripts/dm.json, dm/master/metrics/metrics.go, dm/master/scheduler/scheduler.go
part of #543 
Add panel for worker event error, remove TODO.
Tests 
- Manual test (generate some error and check Grafana)
Code changes
Side effects
=> master: add metric for worker event error

dm/dm-ansible/inventory.ini
now, we build **master** branch nightly as `nightly` version, but let `latest` as the latest **release** version (now, it's `v1.0.6`).
if a user downloads DM-Ansible `nightly`, and then deploy DM directly, they expect the `nightly` version of DM deployed (and not v1.0.6).
change `dm_version` in `inventory.ini` to `nightly`.
Tests 
- No code
=> *: change `dm_version` to `nightly`

pkg/gtid/gtid.go, pkg/gtid/gtid_test.go, pkg/v1dbschema/schema.go, pkg/v1dbschema/schema_test.go, relay/relay.go, relay/relay_test.go
in MySQL, we expect `PreviousGTIDsEvent` contains ALL previous GTID sets, but in fact it may lack a part of them sometimes.
e.g we expect `00c04543-f584-11e9-a765-0242ac120002:1-100,03fc0263-28c7-11e7-a653-6c0b84d59f30:1-100`, but may be `00c04543-f584-11e9-a765-0242ac120002:50-100,03fc0263-28c7-11e7-a653-6c0b84d59f30:60-100`.
and when DM requesting MySQL to send binlog events with this EXCLUDED GTID sets, some errors like `ERROR 1236 (HY000): The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires.` may occur
reset the start part of GTID sets when recovering from relay log or upgrading v1.0.x checkpoint
Tests 
- Unit test
Code changes
Related …
=> fix: reset the start part of GTID sets when recovering from relay log or upgrading v1.0.x checkpoint

go.mod, go.sum, tests/dmctl_command/data/db1.prepare.sql, tests/filter_user_cancel/data/db1.prepare.sql, tests/full_mode/data/db1.prepare.sql, tests/full_mode/run.sh, tests/incremental_mode/data/db1.prepare.sql
manually cherrypick #870 
update tidb-tools and fix some tests
=> precheck: support primary/unique key check #870

dumpling/dumpling.go, dumpling/util.go, syncer/syncer.go
close #880 
- set tls for dumpling
- set tls for streamController
Tests 
start a mysql server with tls config, run an all mode task
=> fix: TLS support for dumpling and syncer in v2.0

dm/master/server.go
`start-task --remove-meta` routine will call `utils.Decrypt` which is not suitable for plain password
replace to `utils.DecryptOrPlaintext`
Tests 
- Manual test (I guess no problem, will test **after** merge in Aurora migration)
Code changes
Side effects
=> master: replace wrong usage of utils.Decrypt

dumpling/dumpling.go, go.mod, go.sum, tests/print_status/run.sh
dump date with column name, so we can support the case:
- more columns exist in downstream than upstream
- different column order between downstream and upstream
- update dumpling
- set `CompleteInsert` to `true`
data dumped before
```sql
INSERT INTO VALUES
(1,1),
(2,2),
(3,3);
```
data dumped now
```sql
INSERT INTO `t1` (`c1`,`c2`) VALUES
(1,1),
(2,2),
(3,3),
```
Tests 
- dump & load data with more columns exist in downstream
Code changes
=> feat: support to dump data with column name

syncer/streamer_controller.go, tests/drop_column_with_index/run.sh
part of https://github.com/pingcap/dm/issues/773
remove wait time to reduce indetermination
Tests 
Code changes
Side effects
=> test: remove wait time to reduce indetermination

dm/config/task.go, mydumper/mydumper.go
cherry-pick #909 
---
part of https://github.com/pingcap/dm/issues/907
retrieve ANSI_QUOTES from upstream, and change subtask config.
disable manually config EnableANSIQuotes of subtask
Tests 
Code changes
Side effects
=> dump: retrieve ANSI_QUOTES from upstream (#909)

dm/worker/worker_test.go
test fails because injected failpoint only fail for 2 times, when test runs slowly, that's not enough
keep fails until we check, then disable it
Tests 
- Unit test
Code changes
Side effects
=> Fix auto resume

pkg/conn/basedb.go, pkg/conn/basedb_test.go
DB connection leak when successful open DB but failed ping.
close it manually. **alternative is we should return `db, error` to caller instead of `nil, error`, so caller's rollback function could handle closing DB**.
Tests 
- unit test
Code changes
Side effects
=> basedb: close db when fail ping

syncer/checkpoint.go, tests/import_v10x/data/v106_syncer_checkpoint.sql
`gen delete sqls failed, schema: import_v10x, table: t2: Column count doesn't match value count: 0 (columns) vs 2 (values)` reported after importing from v1.0.6.
do not create an empty table if `table_info` column is `null`
Tests 
- Unit test
=> fix: handle `null` table_info after importing from v1.0.x

dm/master/config.go, dm/worker/config.go, dm/worker/join.go, pkg/utils/util.go, pkg/utils/util_test.go, tests/ha_master/conf/dm-worker1.toml
check and correct format of addr and URL in config files
for xxx-addr, it should not have a scheme. for xxx-urls and its parent config, such as join, initial-cluster, element in it should have a scheme
Tests 
- Unit test
Code changes
Side effects
- Need to update the documentation [https://github.com/pingcap/docs-dm/pull/303]
=> config: check and correct format of addr and URL

_utils/terror_gen/errors_release.txt, dm/worker/worker_test.go, errors.toml, pkg/streamer/reader_test.go, pkg/terror/error_list.go, syncer/checkpoint.go, syncer/streamer_controller.go, syncer/syncer_test.go, tests/_utils/get_leader, tests/_utils/run_dm_master, tests/_utils/run_dm_worker, tests/_utils/test_prepare, tests/drop_column_with_index/run.sh, tests/full_mode/run.sh, tests/ha_master/run.sh
Co-authored-by: lance6716 <lance6716@gmail.com>
manually cherry-pick #916
fix unstable test cases in CI.
- /run-all-tests to find unstable cases.
- push commit in this pr to fix the cases.
=> Quality reinforcement: fix unstable test cases (#916)

_utils/terror_gen/errors_release.txt, dm/config/source_config.go, dm/master/server.go, errors.toml, pkg/terror/error_list.go, pkg/terror/terror.go, pkg/utils/db.go
close #941 
check whether GTID is `ON` in the upstream when operate-source create
Tests 
run mysql with GTID_MODE=OFF, and set enable-gtid: true in source config
=> source: check whether GTID is `ON` in the upstream ealier

dm/master/server.go
```
panic: runtime error: index out of range [0] with length 0
goroutine 758 [running]:
github.com/pingcap/dm/dm/master.(*Server).listMemberMaster(0xc0002fe3c0, 0x24dcde0, 0xc001af5a70, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc001af5cb0)
/home/jenkins/agent/workspace/build_dm_multi_branch_master/go/src/github.com/pingcap/dm/dm/master/server.go:1870 +0x6aa
github.com/pingcap/dm/dm/master.(*Server).ListMember(0xc0002fe3c0, 0x24dcde0, 0xc001af5a70, 0xc001ae2cc0, 0xc0002fe3c0, 0x24f6200, 0xc00093d080)
/home/jenkins/agent/workspace/build_dm_multi_branch_master/go/src/github.com/pingcap/dm/dm/master/server.go:1989 +0x568
github.com/pingcap/dm/dm/pb._Master_ListMember_Handler.func1(0x24dcde0, 0xc001af5a70, 0x1fe7c20, 0xc001ae2cc0, 0x15, 0xc001aed7c0, 0xc002728701, 0x21b6250) …
```
=> master: fix panic when etcd member not started

pkg/retry/errors.go
fix #921
add this type of error to `UnsupportedDMLMsgs` (can't verify this is the right place)
Tests 
- hard to find a MariaDB 10.0, can't imitate using newer MariaDB and mysql56_temporal_format = OFF
Code changes
Side effects
=> task_checker: don't auto-resume for wrong datetime value

_utils/terror_gen/errors_release.txt, dm/config/task.go, dm/config/task_test.go, errors.toml, pkg/terror/error_list.go
fix #978 
check `binlog-gtid` in `Verify`.
Tests 
- Unit test
=> config: fix `binlog-gtid` verify

syncer/syncer.go, tests/all_mode/run.sh
close #975 
- do not check table exist when drop table because we have added `IF EXIST` for  DROP TABLE statement.
Tests 
=> syncer: table no need exist when drop

dm/master/config.go, dm/master/etcd_test.go, dm/master/server.go
close #974 
- set etcd-log-level to `warn` if log-level is `info`, otherwise set it same as log-level
Tests 
Manually check the log file.
=> log: support change the level of etcd for debugging

dm/worker/server.go, dm/worker/worker.go
close #993 
copy source config to subtask task before `getMinPosInAllSubTasks`
Tests 
use shell script in #993 , currently dmctl_basic integration_test also cover it.
=> relay: fix invalid flavor after restart dm-master

checker/check_test.go, checker/checker.go, checker/cmd.go, dm/config/subtask.go, dm/config/task.go, dm/config/task_test.go, dm/master/server.go, dm/master/server_test.go, dumpling/dumpling.go, go.mod, go.sum, loader/convert_data.go, loader/convert_data_test.go, loader/loader.go, pkg/binlog/event/util.go, pkg/binlog/reader/tcp_test.go, pkg/binlog/reader/util.go, pkg/binlog/reader/util_test.go, pkg/parser/common.go, pkg/utils/db.go, pkg/v1dbschema/schema.go, relay/relay.go, syncer/db.go, syncer/ddl_test.go, syncer/error.go, syncer/handle_error.go, syncer/schema.go, syncer/syncer.go, syncer/syncer_test.go, tests/relay_interrupt/run.sh
manually cherry-pick #889 
---
close #878
- for DB related sqls, query global/session variables and find if set ANSI_QUOTES.
- for binlog related sqls, using https://github.com/pingcap/dm/pull/882.
- some sqls are generated by parser using default flag, so a default parser could handle.
still need user specified ANSI_QUOTES:
- ~dump unit, will check if DM could handle this~
- ~dependency of tidb-tools, could remove after https://github.com/pingcap/tidb-tools/pull/381~
Tests 
- Unit test
Code changes
Side effects
=> *: auto discover ANSI_QUOTES #889

syncer/syncer.go
fix #1038
only skip the fake rotate event if it's not to the next binlog file.
NOTE:
- MySQL server will write a RotateEvent before rotate to the next binlog file normally.
- MySQL server will send a _fake_ RotateEvent to the slave before sending other real binlog events.
- MySQL server will write a StopEvent at the end of a binlog file when stoping itself but without RotateEvent
- MySQL server will write from a new binlog file after started itself
Tests 
- trigger the error reported in #1038 with an older version of DM
- replace DM-worker with a newer version in this PR
- observe the task resumed
Code changes
Side effects
- Need to be included in the …
=> syncer: do not ignore fake rotate event to the next file

dm/master/server.go, tests/tls/run.sh
fix master offline in list-member when use tls.
use tls for http client
Tests 
=> tls: use tls in list-member

loader/checkpoint.go, loader/checkpoint_test.go, loader/loader.go, loader/util.go, tests/all_mode/run.sh, tests/import_goroutine_leak/run.sh
manually cherry-pick #1027 and #1042
---
close #1006
- **keep checkpoint in memory updated with DB**
- don't execute structure SQL when found db/table in checkpoint
- don't repeatly initiate checkpoint record
- only clean dump SQL files when all finished, to keep progress when resuming
Tests 
- Unit test
- Manually check log contains "skip creating it"
Code changes
Side effects
=> loader: don't print ERROR log, clean dump file when all finished (#1027)

dm/master/shardddl/optimist.go, pkg/binlog/reader/util.go, pkg/conn/basedb.go, pkg/conn/basedb_test.go, pkg/shardddl/optimism/info.go, pkg/shardddl/optimism/info_test.go, pkg/shardddl/optimism/keeper.go, pkg/shardddl/optimism/lock.go, pkg/shardddl/optimism/lock_test.go, pkg/shardddl/optimism/ops.go, pkg/shardddl/optimism/ops_test.go, syncer/shardddl/optimist_test.go, tests/shardddl3/run.sh
- second ddl's lock may be deleted when first ddl resolved.
- new info putted to etcd may be deleted when previous ddl resolved
- add lock in handleInfo and handleOperation to avoid concurrency conflict
- record the version of info, only delete info if all version of info are greater or equal then that in etcd.
Tests 
- Unit test
=> shardddl: add lock and version for optimistic info

syncer/optimist.go, syncer/syncer.go, tests/handle_error/run.sh
close #984 
- report error when execute ddl fail in dowsteam TiDB
- omit error in syncDDL caller to avoid duplicate error message
Tests 
=> ddl: pause subtask when exec ddl err

syncer/dml.go, syncer/dml_test.go
KEY index will be added in DML concurrency keys, which will slow the sync.
remove it
Tests 
- Unit test
Code changes
Side effects
=> syncer: remove KEY index in DML concurrency keys

_utils/terror_gen/errors_release.txt, dm/config/subtask.go, dm/worker/worker.go, errors.toml, loader/status.go, pkg/conn/basedb.go, pkg/retry/errors.go, pkg/schema/tracker.go, pkg/schema/tracker_test.go, pkg/terror/error_list.go, syncer/checkpoint_test.go, syncer/status.go, syncer/syncer.go, syncer/syncer_test.go, tests/sharding/conf/dm-task.yaml, tests/sharding/run.sh
manually cherry-pick #1032
---
enable some test about altering PK, and reduce user config. close #1003 
- session variable:
- if user specified, use it
- else get `sql_mode`, `tidb_skip_utf8_check` from downstream
- tracker (tidb) config:
- set `alter-primary-key` true
- max-allow-packet
- always get from downstream (by feature of driver)
Tests 
- Unit test
Code changes
Side effects
=> tracker: get some session variables from downtream (#1032)

pkg/retry/errors.go
ignore more unrecoverable error from https://docs.pingcap.com/zh/tidb/stable/tidb-limitations. some errors are not generated in MySQL and TiDB (partition number limit) so omitted.
add more error message
Tests 
get these message from latest TiDB
Code changes
Side effects
=> task_checker: ignore more unrecoverable error

dm/config/task.go, mydumper/mydumper.go
This reverts commit 3b16803e32c8ce9d6d1e43f4d273288dc2a8be25. Because isolated dump unit auto discover will save ANSI_QUOTES into subtask config, which cause sync unit can't work
revert #929
Tests 
Code changes
Side effects
=> Revert "dump: retrieve ANSI_QUOTES from upstream (#909) (#929)"

go.mod, go.sum, tests/all_mode/run.sh
close #1119, part of #1130
https://github.com/pingcap/dumpling/pull/157 : dumpling add `--allow-cleartext-password`
https://github.com/pingcap/dumpling/pull/158 : dumpling support dump view, but default don't dump it (need more test to default enable)
https://github.com/pingcap/dumpling/pull/160 : set default `statement-size`
Tests 
- No code
Code changes
Side effects
=> dep: update dumpling

loader/loader.go, tests/all_mode/conf/dm-task.yaml, tests/all_mode/data/db1.prepare.sql, tests/all_mode/run.sh
fix bug that loader didn't use SQL Mode when create database connections, this bug is not revealed because `all_mode` has manually set SQL Mode related config
if `to` database doesn't have a `sql_mode` item, we use SQL Mode discovered by dumpling's `Init`.
Tests 
Code changes
Side effects
=> loader: fix bug that SQL Mode didn't take effect

dumpling/dumpling.go, tests/full_mode/data/db1.prepare.sql, tests/full_mode/run.sh
part of #1130
because loader will use upstream's SQL mode, if upstream has `NO_BACKSLASH_ESCAPES`, we should not escape `\` in dump files.
Tests 
Code changes
Side effects
=> dumpling: properly enable EscapeBackslash with upstream SQL mode

dm/config/source_config.go, dm/config/task.go, dm/config/task_test.go, dumpling/dumpling_test.go
close #1130
till this PR, all default config is checked and should cause no problem (I hope)
Tests 
- Unit test
Code changes
Side effects
=> config: check default config

syncer/checkpoint.go, syncer/syncer.go
close #1172
for lease change, when update/delete checkpoint in DB, use a new context with 5-minute timeout, to avoid syncer's `cancel()` did not let SQL commit. 
create checkpoint is only called at syncer's `Init`, seems OK to be canceled
read checkpoint doesn't have a side effect, OK to be canceled
those methods are called from `Run -> handleQueryEvent`, which may block when pause/stop. Maybe we need https://github.com/pingcap/dm/pull/605
Tests 
- Pass original test
Code changes
Side effects
=> syncer/checkpoint: ignore cancel for update/delete

dumpling/util.go, dumpling/util_test.go
when specifed `extra-args`, `parseExtraArgs` will overwrite `FileSize` set in other place
check in `parseExtraArgs`
Tests 
- Unit test
Code changes
Side effects
=> dumpling: fix default values changed when specified extra-args

dumpling/util.go, dumpling/util_test.go
in dumpling, we use `-s` as the shorthand for `--statement-size` (https://github.com/pingcap/dumpling/blob/270170441a02b0a31ea927ae3ffb13c4acb8dc23/cmd/dumpling/main.go#L102), but we use `-S` in DM.
change `S` to `s`.
Tests 
- Unit test
Code changes
Side effects
=> fix: fix wrong shorthand for `statement-size`

cmd/dm-ctl/main.go
`exit` with trailing white spaces
```
» exit
Error: unknown command "exit" for "dmctl"
Run 'dmctl --help' for usage.
fail to run: [exit]
```
`exit` with leading white spaces
```
»  exit
Error: unknown command "exit" for "dmctl"
Run 'dmctl --help' for usage.
fail to run: [exit]
```
remove leading and trailing white spaces before handling it.
Tests 
- re-run commands above
Code changes
Side effects
=> fix: accept comands with leading and trailing white spaces

loader/loader.go, loader/util.go, loader/util_test.go
fix #1255 
use `LastIndex` rather than `Index` to find the index of `.sql` suffix.
Tests 
- Unit test
Code changes
Side effects
=> fix: support "sql" prefix exists in table name

dm/master/shardddl/pessimist.go, tests/_utils/test_prepare, tests/shardddl3/run.sh
close #1253 
```
[2020-10-30T02:25:09.879Z] [2020/10/30 10:24:51.715 +08:00] [INFO] [pessimist.go:522] ["the lock for the shard DDL lock operation has been resolved"] [component="shard DDL pessimist"] [operation="{\"id\":\"test-`shardddl`.`tb`\",\"task\":\"test\",\"source\":\"mysql-replica-02\",\"ddls\":[\"ALTER TABLE `shardddl`.`tb` ADD UNIQUE `idx_a`(`a`)\"],\"exec\":false,\"done\":true}"]
[2020-10-30T02:25:09.879Z] [2020/10/30 10:24:51.818 +08:00] [INFO] [pessimist.go:466] ["receive a shard DDL info"] [component="shard DDL pessimist"] [info="{\"task\":\"test\",\"source\":\"mysql-replica-01\",\"schema\":\"shardddl\",\"table\":\"tb\",\"ddls\":[\"ALTER TABLE `shardddl`.`tb` ADD UNIQUE `idx_b`(`b`)\"]}"]
[2020-10-30T02:25:09.880Z] [2020/10/30 10:24:51.818 +08:00] [ERROR] [pessimist.go:472] …
```
=> shardddl: add infoOpLock for pessmist shardddl

dm/worker/server.go, syncer/checkpoint.go, syncer/checkpoint_test.go, syncer/syncer.go, tests/start_task/run.sh
close #1260 
create table in tracker when get table first time.
Tests 
=> schemaTracker: lazy init table info in schema tracker

syncer/handle_error.go, syncer/syncer.go, tests/handle_error/run.sh
only support handle query error to avoid misuse
add a check when handle-error
Tests 
=> handle-error: only support to handle query error

syncer/syncer.go, tests/all_mode/data/db2.increment.sql
Inconsistent upstream and downstream sql_mode leads to inconsistent data
get dsn scope sql_mode from upstream database if sql_mode is not specified in task config.
**Still can't use different session sql_mode base on different binlog event like mysql master-slave replication. One solution is get sql_mode from `begin` event and apply it for rows event in same txn, which is ineffective.**
Tests 
=> sycner: automatically use upstream sql_mode

chaos/manifests/io-chaos-dm.yaml
in https://github.com/pingcap/dm/runs/1504712775?check_suite_focus=true, an error occurs 
```
error: error validating "./chaos.yaml": error validating data: ValidationError(IoChaos.metadata): unknown field "lables" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta; if you choose to ignore these errors, turn validation off with --validate=false]
```
maybe remove `lables` field could help? latest chaosmesh example shows there's no `labels` now
and don't know why other chaos jobs didn't fail
Tests 
- No code
Code changes
Side effects
=> chaos: Update io-chaos-dm.yaml

syncer/syncer.go
row event's currentLocation not update due to #1303 
in #1303, we disable handle-error for rows event, but also skip [update currentLocation](https://github.com/pingcap/dm/blob/7e79861c53544a13c237fb680b8571af4f676fff/syncer/syncer.go#L1362) by mistake.
update currentlocation in handleRowEvents
Tests 
manually test
add more auto test for transaction later.
=> bug-fix: fix currentLocation not increase in rows event

pkg/utils/util.go, syncer/filter_test.go, syncer/syncer_test.go, tests/others_integration.txt, tests/safe_mode/data/db1.increment.sql, tests/safe_mode/data/db2.increment.sql
- add test for #1329
- revert VIEW support for #1105 because we choose to support sync VIEW later
- filter out EVENT by builtin regular expression, close https://github.com/pingcap/dm/issues/1342
Tests 
- Unit test
Code changes
Side effects
=> *: add test for #1329 and add VIEW & EVENT in builtin filter

chaos/cases/config.go, chaos/cases/diff.go, chaos/cases/task.go
- chaos test will always return true when diff incremental data 😨
- alter table add column(timestamp) will have different default value between mysql:5.7 and tidb.
- change context
- add session variable `explicit_defaults_for_timestamp`
Tests 
- chaos test
=> chaos: fix diffIncrData has no effect

pkg/streamer/reader_test.go, pkg/streamer/streamer.go, pkg/streamer/streamer_test.go
currently relay will ignore heartbeat event before writing to relay logs. so when relay enabled, there's no heartbeat event which causes syncer can't advance its checkpoint when upstream is idle.
peroidically send heartbeat event
Tests 
- Unit test
- Manually test (only do an insert in upstream, and check checkpoint advanced after 30s)
Code changes
Side effects
=> streamer: add heartbeat for local streamer

pkg/streamer/reader.go
in #1364, channels are closed in a goroutine when context is done, so in afterwards `select { case v := <- ch` we will read a `v` of zero value, which will cause wrong logic
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8147/pipeline/72/
we don't need to close channels if they are no longer referenced, gc will correctly clean them. (but if the values in channel need a explict `Close`, we should drain the channel and `Close` each one)
https://nanxiao.gitbooks.io/golang-101-hacks/content/posts/need-not-close-every-channel.html
Tests 
- hard to test
Code changes
Side effects
- Need to cherry-pick to the release branch (will cherry-pick to https://github.com/pingcap/dm/pull/1420 manually)
=> streamer: fix unstable CI introduced in #1364

dm/dm-ansible/scripts/dm.json
there's two `"id": 5` and `x, y = 12, 17` panels
Tests 
- No code
Code changes
Side effects
=> grafana: fix duplicate panel id and position

pkg/conn/basedb.go
as described in title
add timeout of 30s for ping
Tests 
- pass original test, hard to test I think
Code changes
Side effects
=> conn: add timeout for ping

_utils/terror_gen/errors_release.txt, dm/master/server_test.go, dm/master/shardddl/optimist_test.go, errors.toml, pkg/ha/keepalive.go, pkg/shardddl/optimism/info.go, pkg/shardddl/optimism/info_test.go, pkg/shardddl/optimism/keeper.go, pkg/shardddl/optimism/keeper_test.go, pkg/shardddl/optimism/lock.go, pkg/shardddl/optimism/lock_test.go, pkg/terror/error_list.go, relay/meta_test.go, syncer/optimist.go, syncer/shardddl/optimist.go, syncer/shardddl/optimist_test.go, tests/shardddl2/run.sh
support combine ddls like `alter table add column col4 int, drop column col3;` for optimistic sharding mode
send all table infos to master per split ddl, master join theme one by one.
Tests 
- Unit test
=> shardddl: support combine ddls in one sql for optimistic sharding mode

dm/ctl/ctl.go
align with https://github.com/pingcap/docs-dm/pull/560
overwrite builtin help command
Tests 
```
» help
DM control
Usage:
dmctl [command]
Available Commands:
check-task      Checks the configuration file of the task.
get-config      Gets the configuration.
handle-error    `skip`/`replace`/`revert` the current error event or a specific binlog position (binlog-pos) event.
help            Gets help about any command.
```
=> dmctl: change help message

loader/convert_data.go, loader/loader.go, tests/safe_mode/conf/dm-task.yaml, tests/safe_mode/data/db1.prepare.sql, tests/safe_mode/data/db2.prepare.sql, tests/safe_mode/run.sh
in https://github.com/pingcap/dm/pull/1309, condition branch of dumped data file is not tested because of column-mapping, and it has a BUG
don't use ANSI_QUOTES for dumped data files
Tests 
=> loader: don't use ANSI_QUOTES for dumped data files

dm/ctl/ctl.go, pkg/shardddl/optimism/lock.go, pkg/shardddl/optimism/lock_test.go, tests/handle_error/run.sh
close #1484 
If a ddl conflict with previous one, do not update table info in master, so we can use handle-error replace to replace a new ddl and no conflict.
Tests 
- Unit test
=> optimist: only update table info if no conflict

_utils/terror_gen/errors_release.txt, dm/common/common.go, errors.toml, pkg/ha/bound.go, pkg/ha/relay.go, pkg/ha/relay_test.go, pkg/terror/error_list.go, relay/retry/reader.go
part of support `start-relay` of one source to many workers
add etcd key prefix, k/v: worker-name -> source-id
Tests 
- Unit test
Code changes
Side effects
=> ha: add RelayConfig related function

tests/sequence_sharding_optimistic/run.sh, tests/shardddl3/conf/tidb-alter-pk-config.toml, tests/shardddl3/run.sh
revert some of https://github.com/pingcap/dm/pull/1522
Tests 
- No code
=> test: align with TiDB clustered index behaviour

tests/sequence_sharding_optimistic/data/db1.increment.sql, tests/sequence_sharding_optimistic/data/db1.increment2.sql, tests/shardddl1/run.sh, tests/shardddl3/run.sh
fix https://github.com/pingcap/dm/pull/1540#issuecomment-809451583
move add column after a sync-diff check
Tests 
- No code
Code changes
Side effects
=> test: fix unstabled drop then add column

dm/master/shardddl/optimist.go, dm/master/shardddl/optimist_test.go, pkg/shardddl/optimism/schema.go, pkg/shardddl/optimism/schema_test.go, tests/_utils/test_prepare, tests/shardddl3/run.sh
In #1518, we always use table-info-before to rebuild locks, but ignore the upstream table who has no optimism.Info. In such a case, we may build an incorrect joined table.
Suppose there are two upstream tables tb1(a int, b int, c int) and tb2(a int, b int, c int).  A possible time series is:
```
t1: tb1 and tb2 are identical.
t2: tb1 drop column b, c.
t3: restart.
t4: joined becomes tb1's table-info-before, which is tb(a int). // The correct joined should be tb(a int, b int, c int).
```
Use init-schema for table without info when recover lock.  If there is no optimism.Info for a upstream table, it indicates the table structure hasn't been changed since last removeLock. So the init schema should be its table info.
Tests 
- Unit test
=> shardddl/optimistic: use init-schema for table without info when recover lock

dm/dm-ansible/scripts/dm.json, dm/dm-ansible/scripts/dm_instances.json, dm/worker/metrics.go, dm/worker/subtask.go, tests/_utils/check_metric_not_contains, tests/all_mode/run.sh, tests/full_mode/run.sh
fix #1594
delete taskState when task is stopped/finished
Tests 
- Unit test
When task is running:
```
dm_worker_cpu_usage 3.528409857613362
dm_worker_task_state{source_id="mysql-replica-01",task="testdm"} 2
```
After task is stopped:
```
dm_worker_cpu_usage 3.521312888533776
go_gc_duration_seconds{quantile="0"} 2.6124e-05
go_gc_duration_seconds{quantile="0.25"} 3.0232e-05
```
=> worker: delete taskState when task is stopped/finished

cmd/dm-ctl/main.go, dm/ctl/common/config.go, dm/master/metrics/metrics.go, dm/worker/worker.go, tests/dmctl_command/run.sh
#1564 
dmctl：print help msg when user input `--help` before validate the dmctl config
Tests 
- Unit test
Code changes
- `cmd/dm-ctl/main.go`
- `dm/ctl/common/config.go `
Side effects
- None
=> dmctl: show help msg before validate cfg #1564

dm/master/scheduler/scheduler.go, dm/master/scheduler/scheduler_test.go, dm/master/server.go, dm/master/workerrpc/rawgrpc.go
part 2 of https://github.com/pingcap/dm/issues/1636
dm-master didn't close grpc connections before it close scheduler.
Close `scheduler.workers` grpc connections when scheduler fails to start or trying to Close.
Tests 
- Unit test
Code changes
=> scheduler: close workers grpc connections timely

dm/master/server.go, dm/master/server_test.go, dm/worker/worker.go, dm/worker/worker_test.go, pkg/utils/common.go, tests/sequence_sharding_removemeta/run.sh
some users don't use `show-ddl-locks` to get unsynced tables, they use `query-status` instead, so we also show reasonable message in `query-status`
- re-fill the related field
- also fix a BUG that forget to decrypt password before open connection to upstream which introduced in https://github.com/pingcap/dm/pull/1619
Tests 
Code changes
- Has (user) interface methods change
=> *: show an unsynced message for workers which didn't get any shard DDL

_utils/terror_gen/errors_release.txt, dm/master/server.go, dm/worker/worker.go, errors.toml, pkg/terror/error_list.go, pkg/upgrade/upgrade.go, pkg/upgrade/upgrade_test.go, pkg/upgrade/version.go, pkg/utils/common.go, syncer/ddl.go, syncer/online_ddl.go, syncer/syncer.go, tests/dmctl_basic/run.sh, tests/online_ddl/conf/dm-task.yaml, tests/online_ddl/data/db1.increment2.sql, tests/online_ddl/data/db2.increment2.sql, tests/online_ddl/run.sh, tests/sequence_sharding_removemeta/run.sh
close https://github.com/pingcap/dm/issues/1656
- save an empty SQL when online DDL is filtered, and remove it when read it from online DDL component
- use `?` not fmt.Sprintf to build a query
Tests 
Code changes
- Has persistent data change (not likely, because if there's quote in source-id, an error already occurred)
Side effects
=> syncer: save empty SQL when online DDL is filtered

syncer/err-operator/operator.go, syncer/err-operator/operator_test.go, syncer/syncer.go
close #1763 
Replaces the timestamp of the real event header with the event generated by the dm.
Tests 
- Unit test
Code changes
- None
Side effects
=> syncer: fix replication lag when hanle-error

syncer/checkpoint.go, syncer/checkpoint_test.go, syncer/syncer.go, tests/all_mode/data/db1.increment3.sql, tests/all_mode/data/db2.increment3.sql, tests/all_mode/run.sh
manually cherry-pick #1752
---
Tests 
- Unit test
- No code
Code changes
Side effects
=> syncer: don't skip jobs from same event when comparing table checkpoint (#1752)

go.mod, go.sum, pkg/streamer/reader.go
close https://github.com/pingcap/dm/issues/1826
Tests 
- benchmark 1
using sysbench, but change the `k` column to decimal (40, 16). start a v5.0.1 TiDB in same host with DM (in short of VM 😢)
without this PR: dm-worker CPU ~250%, TiDB CPS 18.0k
with this PR: dm-worker CPU ~250%, TiDB CPS 19.5k
- benchmark 2
using sysbench like above, start a v4.0.13 TiDB in another host. task concurrency is 96.
without this PR: dm-worker CPU mean 148%, 147%, TiDB CPS 10.0k
with this PR: dm-worker CPU mean 143%, 146%, TiDB CPS 10.0k
the decodeDecimal only occupied 3.5% CPU, so the optimization takes a little effects.
=> dep: update go-mysql to introduce DECIMAL optimization

pkg/binlog/common/replication.go, pkg/binlog/reader/file.go, pkg/binlog/reader/tcp_test.go, pkg/binlog/reader/util_test.go, pkg/v1dbschema/schema.go, syncer/db_test.go, syncer/filter_test.go
in https://github.com/pingcap/dm/pull/1837 I forget to set all `UseDecimal` and `SetUseDecimal` to `false` 😂 
as title
Tests 
- pass original test
=> syncer, binlog: set all UseDecimal to false

.github/workflows/binlog-999999.yml, .github/workflows/chaos-mesh.yml, .github/workflows/check-and-build.yml, .github/workflows/upgrade-via-tiup.yml, .github/workflows/upstream-switch.yml, syncer/syncer.go, tests/_utils/send_lark_notify.go, tests/_utils/test_prepare, tests/metrics/run.sh
as title
* only print log when enable failpoint
* do not truncate log file when run test case
* use go scripts to send feishu notify when test failed
Tests 
Code changes
Side effects
=> chore: remove no job in queue log

go.mod, go.sum, pkg/retry/errors.go, syncer/dbconn/db.go
Auto retry for ~`mysql.ErrInvalidConn`~ and tidb's `kv.RetryableErr` (by https://github.com/pingcap/tidb-tools/pull/452). 
close #1825
- ~When sql client interrupt (e.g. manually killed by `kill tidb xxx`), go-mysql will return `mysql.ErrInvalidConn` and this error is safe to auto-retry build the connection~
- tidb's `kv.RetryableErr` (currently only caused by TxnLockNotFound) is retryable too.
Tests 
- Unit test
Code changes
Side effects
=> syncer/dbconn: add more retry error

dm/worker/subtask.go, dm/worker/subtask_test.go, syncer/streamer_controller.go, tests/drop_column_with_index/run.sh
close #1729 
TaskChecker will not resume a task that is manually paused(isCancel: true)
When users manual pauses a task which has been pause by error(task stage is paused while isCancel is false), mark the isCancel to true.
Tests 
- Unit test
- No code
Code changes
Side effects
=> *: manual pause a task which has been pause by error

syncer/syncer.go, tests/all_mode/data/db2.increment3.sql, tests/all_mode/run.sh, tests/case_sensitive/run.sh, tests/ha/run.sh, tests/metrics/run.sh
as title, since many events share a same GTID, the checking of exitSafeMode should not use `equal` otherwise some partitially replicated GTID will cause duplicate entry error.
we now make sure the replication progress is later (not equal) than exitSafeModePoint when exit safe-mode
Tests 
=> syncer: fix safemode exit too early

syncer/optimist.go, syncer/syncer.go
handleQueryEvent is too big 😂 
depends on different shard mode, program will go to `handleQueryEventNoSharding`, `handleQueryEventOptimistic`, `handleQueryEventPessimistic`
Tests 
- pass original tests
=> syncer: split functions of different shard mode

pkg/election/election.go, tests/ha_master/run.sh
close https://github.com/pingcap/dm/issues/1983
when `Campaign` returned an error, always try to clean last election key
Tests 
- hard to test
=> election: always try to clean last election key

tests/all_mode/run.sh, tests/case_sensitive/run.sh, tests/gtid/run.sh, tests/metrics/run.sh, tests/only_dml/run.sh
part of https://github.com/pingcap/dm/issues/1997
- when a task is started some time is needed to `Init` units, only after `Init` the task goes to Running status, so wait more to pass `Init`
- worker is restarted, retry `query-status` to see if error is gone
Tests 
- No code
=> test: fix unstable metrics test

dm/master/scheduler/scheduler.go, dm/master/scheduler/scheduler_test.go
close #2002
If some worker are offline during master leader transfer, the offline event will be missing. So scheduler should try to bind free source and worker if any after initilized.
Tests 
- Unit test
Code changes
Side effects
=> scheduler: try bind free worker to source in start scheduler

dm/ctl/common/config.go, dm/ctl/ctl.go
close #1988 
dmctl will always try to parse --config(even it will not be used) and treat it as the dmctl config, that's the reason of err in this case, and if the --config is actually needed and can't be parsed correctly, it will cause the same err, add log to make it more readable
Tests 
- No code
Code changes
Side effects
=> dmctl: add config err log

loader/db.go, syncer/dbconn/db.go
Add more accurate log messages to slow SQL.
When the SQL execution time exceeds 1 second, an accurate slow SQL warning will be prompted.
Tests 
- No code
=> syncer, loader: make warn log message more accurate

Makefile
part of #1997 , some unit tests will timeout
in #1709 we add a 2m timeout, that's tight now. For a success CI, we can see some slow unit test
```
[2021-08-24T08:56:29.459Z] ok  	github.com/pingcap/dm/dm/master	87.674s	coverage: 62.3% of statements
[2021-08-24T08:56:31.994Z] ok  	github.com/pingcap/dm/dm/master/shardddl	100.157s	coverage: 77.0% of statements
[2021-08-24T08:57:04.080Z] ok  	github.com/pingcap/dm/dm/worker	101.352s	coverage: 71.7% of statements
[2021-08-24T08:57:04.081Z] ok  	github.com/pingcap/dm/pkg/streamer	70.131s	coverage: 89.7% of statements
```
so when CI node is slow, there's chance that unit test will timeout
Tests 
- No code
=> test: increase unit test timeout

pkg/schema/tracker.go
reduce CPU consumption
as title, ref https://docs.pingcap.com/zh/tidb/stable/tidb-configuration-file#stats-lease
Tests 
- No code
=> tracker: disable background statistic job

tests/_utils/check_rpc_alive
part of https://github.com/pingcap/dm/issues/2073
https://ci.pingcap.net/blue/organizations/jenkins/dm_ghpr_new_test/detail/dm_ghpr_new_test/2218/pipeline/ :
- waiting MySQL2 starting cost 32 * 2s
- some DM-master printed `init now`and `dm-master startup ...` to stdout
- some DM-master printed `init now` to stdout
and https://ci.pingcap.net/blue/organizations/jenkins/dm_ghpr_new_test/detail/dm_ghpr_new_test/2143/pipeline/ :
- DM-master print nothing
increase retry from 10 times to 20 times 😂 
Tests 
- No code
=> test: fix unstable wait rpc alive

syncer/error.go
In https://github.com/pingcap/tidb/pull/18852, TiDB has changed error message from `with index` to `with composite index`. In https://github.com/pingcap/tidb/pull/27500, TiDB is constrained more strictly on drop columns with indices. So the test with TiDB nightly failed.
Add check for new format message too.
Tests 
- Unit test
=> test: fix can't drop column with index problem

dm/dm-ansible/scripts/DM-Monitor-Professional.json, dm/dm-ansible/scripts/DM-Monitor-Standard.json
close #2107 
in #1778  we add some new dashboard but forgot to add grafana datasource variable `${DS_TEST-CLUSTER}` in dashboard json, so grafana will choose to use default datasource(grafana random walk)
related to  https://github.com/nginxinc/nginx-prometheus-exporter/pull/71
Tests 
test fixed dashboard with my local mac
pro:
standard:
- No code
Code changes
Side effects
=> grafana: fix grafana dashboard

tests/_utils/test_prepare, tests/all_mode/run.sh
integration test: fix invalid pgrep expression which may cause case fail sometime; add sleep to all_mode test(may fail sometimes)
some integration test case(all_mode) may fail sometimes(when process doesn't exit fast enough or delayed)
- fix `pgrep` expression in `wait_pattern_exit`
- add `sleep 2` to integration test case `all_mode`
Tests 
- No code
=> test: fix integration test which may cause case fail sometimes

dm/master/agent_pool_test.go, dm/master/election_test.go, dm/master/server_test.go, pkg/election/election_test.go, pkg/streamer/reader_test.go
part of https://github.com/pingcap/dm/issues/2073
as title
Tests 
- Unit test
Code changes
Side effects
=> test: fix ctx timeout in advance before test success in ut

go.mod, go.sum, syncer/syncer_test.go
as title
[change go-mysql to store json as string](https://github.com/go-mysql-org/go-mysql/pull/658) and update dependency version
Tests 
- Unit test
- No code
Code changes
Side effects
=> support json type for mysql downstream
